### PR TITLE
gmp: add version 6.1.0

### PR DESCRIPTION
**Pull request by FreddieChopin**
Signed-off-by: Freddie Chopin <freddie.chopin@gmail.com>

### CODE REVIEW

**Comment by bhundven** [comment]
Is this tested with older binutils and gcc combinations?
I would say for binutils, only test 2.23.2, 2.24, and 2.25.1, as soon that's all that will be available.

**Comment by FreddieChopin** [comment]
IS there a script (or a way) to test that automatically? Or should I just create required configs and build them? Generally GCC's docs always say "gmc version x.y.z or later" and it usually worked fine with the most recent version (;

**Comment by bhundven** [comment]
I realize this might work with a recent version, but it needs to be tested with all versions crosstool-ng supports. There really isn't a way to automatically do that at this time, and there are only 3 gcc versions and 3 binutils versions you need to worry about, as I mentioned in my previous response. :)

**Comment by bhundven** [comment]
If it doesn't work, then you need to make sure the newer version depends only on the newer versions of gcc and/or binutils.

**Comment by bhundven** [comment]
I went back and tested the worst case scenario binutils-2.23.2, and gcc-4.8.5, and the build worked fine. Merging.

**Pull request merged**
