### PR TITLE
Janitorial: update patches

### PR DESCRIPTION
**Pull request by KirillSmirnov**
This changeset removes patches for obsolete packages and package versions that are not supported by current ct-ng. Bogus patches that do not fix anything are removed too.
New official patches for mpfr and gmp are added.
More fixes for building with recent gcc.

### CODE REVIEW

**Comment by bhundven** [comment]
I dislike large PRs. In the future, if there are more then 5 commits in the PR, break them up into separate PRs. It just takes me a long time to go through each commit. It is what it is, so just leave it the way it is for now, and try not to do that in the future. This is one of the reasons the multilib PR took so long.

**Comment by bhundven** [comment]
Please update with master

**Comment by KirillSmirnov** [comment]
I'm sorry, no more large PRs.

**Comment by bhundven** [comment]
Can you update this PR?

**Comment by KirillSmirnov** [comment]
> Can you update this PR?

Done!

**Comment by KirillSmirnov** [comment]
ping?

**Comment by bhundven** [comment]
For whatever reason, travis-ci is having issues with https. I'll look into this later today.

**Comment by bhundven** [comment]
Come to find out that travis-ci's default build image is ubuntu precise 12.04.
The ssl keys are now out of date enough that kernel.org has already updated their key and now it doesn't match.

Luckily, they have a beta for trusty 14.04. I have #466 open to resolve that issue.

**Comment by stilor** [comment]
I plan to pick up this change next, once my build machine runs through the full set of samples to establish a passing baseline.

LGTM, one question: is there a reason to keep all the GMP versions that we have? Perhaps, remove all but the most recent on each release branch (i.e., keep 4.3.2, 5.0.2, 5.1.3, 6.0.0a and 6.1.2; remove the rest)? I am not suggesting to do it in this PR; it is big enough already :)

**Comment by KirillSmirnov** [comment]
I would remove all obsolete minor/patchlevel versions, not only gmp, but gdb 6.8a, strace 4.5.* too. They are really old and bring pain (especially strace) :-)
I kept these old version just to make the PR as invasive as possible.

**Pull request merged**
