### PR TITLE
Glibc cleanup

### PR DESCRIPTION
**Pull request by bhundven**
This is the long needed glibc cleanup.

There is still more work to do to clean up this glibc script, but this is a good stopping point for now.

### CODE REVIEW

**Comment by mingwandroid** [comment]
On OS X I got:
[ALL  ]    LC_ALL=C /bin/sh ./gen-8bit-gap.sh ../localedata/charmaps/CP774 > /Volumes/CrosstoolNG/raspi2-glibc-cleanup/.build/armv7-rpi2-linux-gnueabihf/build/build-libc-final/iconvdata/cp774.T
[ALL  ]    LC_ALL=C /bin/sh ./gen-8bit-gap-1.sh ../localedata/charmaps/ISO-8859-7 > /Volumes/CrosstoolNG/raspi2-glibc-cleanup/.build/armv7-rpi2-linux-gnueabihf/build/build-libc-final/iconvdata/iso8859-7jp.T
[ALL  ]    make[3]: *** No rule to make target `/Volumes/CrosstoolNG/raspi2-glibc-cleanup/.build/armv7-rpi2-linux-gnueabihf/build/build-libc-final/iconvdata/IBM1388.so', needed by `others'.  Stop.
[ALL  ]    make[3]: *** Waiting for unfinished jobs....
[ALL  ]    /bin/sh ../scripts/move-if-change /Volumes/CrosstoolNG/raspi2-glibc-cleanup/.build/armv7-rpi2-linux-gnueabihf/build/build-libc-final/iconvdata/iso8859-7jp.T /Volumes/CrosstoolNG/raspi2-glibc-cleanup/.build/armv7-rpi2-linux-gnueabihf/build/build-libc-final/iconvdata/iso8859-7jp.h
[ALL  ]    /bin/sh ../scripts/move-if-change /Volumes/CrosstoolNG/raspi2-glibc-cleanup/.build/armv7-rpi2-linux-gnueabihf/build/build-libc-final/iconvdata/cp774.T /Volumes/CrosstoolNG/raspi2-glibc-cleanup/.build/armv7-rpi2-linux-gnueabihf/build/build-libc-final/iconvdata/cp774.h

**Comment by mingwandroid** [comment]
Aah, I always forget that Apple don't write real operating systems, just toys. Elsewhere in the logs there's:

`Too many open files`

**Comment by bhundven** [comment]
@mingwandroid I followed this one: http://unix.stackexchange.com/questions/108174/how-to-persist-ulimit-settings-in-osx-mavericks

**Comment by bhundven** [comment]
This info will definitely be updated in the documentation as a build pre-req.

**Comment by mingwandroid** [comment]
I used:

```ulimit -S -n 8192
sysctl -w kern.maxfiles=20480
sysctl -w kern.maxfilesperproc=18000```

and had a build that got as far as:

```[INFO ]  Installing cross-gdb
[ERROR]    configure: error: python is missing or unusable```

Ah Python, our old friend.

**Comment by bhundven** [comment]
You got as far as cross-gdb with localedef enabled?

**Comment by bhundven** [comment]
My build ends like this:

```
[INFO ]  Installing pass-2 core C gcc compiler: done in 1036.00s (at 78:39)
[INFO ]  =================================================================
[INFO ]  Installing C library
[EXTRA]    Configuring C library
[EXTRA]    Building C library
[EXTRA]    Installing C library
[EXTRA]    Configuring C library localedef
[ERROR]    checking sysdep dirs... configure: error: Operating system darwin15.3.0 is not supported.
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing C library'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@259]
[ERROR]  >>        called from: do_libc_locales[scripts/build/libc/glibc.sh@584]
[ERROR]  >>        called from: do_libc_backend_once[scripts/build/libc/glibc.sh@478]
[ERROR]  >>        called from: do_libc_backend[scripts/build/libc/glibc.sh@139]
[ERROR]  >>        called from: do_libc[scripts/build/libc/glibc.sh@57]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@650]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/Volumes/crosstool-ng/local/share/doc/crosstool-ng/crosstool-ng-1.22.0-97-g5d24846-dirty/B - Known issues.txt'
[ERROR]   
[ERROR]  (elapsed: 95:38.00)
[95:38] / /Volumes/crosstool-ng/local/bin/ct-ng:152: recipe for target 'build' failed
gmake[1]: *** [build] Error 1
/Volumes/crosstool-ng/local/bin/ct-ng:155: recipe for target 'build.1' failed
gmake: *** [build.1] Error 2
```

**Comment by bhundven** [comment]
As per conversation with @mingwandroid, I've dropped the localedef fix for now. We're just moving forward with the glibc_cleanup part.

**Pull request merged**
