### PR TITLE
Initial changes to build cross compilers on new ARM based M1 Macs

### PR DESCRIPTION
**Pull request by galak**

### CODE REVIEW

**Review by cpackham — APPROVED** [review]

**Comment by cpackham** [comment]
Looks good to me, not particularly invasive. I do have the same concerns as the other macOS stuff (basically you're on the hook for debugging any issues). I've got a nice shiny pinebookpro so I could technically test building on ARM but no plans to get any Apple gear.

**Comment by galak** [comment]
> Looks good to me, not particularly invasive. I do have the same concerns as the other macOS stuff (basically you're on the hook for debugging any issues). I've got a nice shiny pinebookpro so I could technically test building on ARM but no plans to get any Apple gear.

Happy to help as best I can when issues come up.

**Comment by mobileoverlord** [comment]
@galak I've been testing this out, but everything errors with errors like `ld: warning: ignoring file ../lib/libm4.a, building for macOS-arm64 but attempting to link with file built for macOS-arm64` and resulting in `Undefined symbols for architecture arm64` any advise?

**Comment by galak** [comment]
What target are you building for?

**Comment by mobileoverlord** [comment]
I’m building for armv7 gnuabihf, I’ve noticed that it fails on the first thing it attempts to build. In this case, it’s failing as soon as it attempts to build m4, but if I disable m4 it fails the exact same way on ncurses.

**Comment by galak** [comment]
Interesting, are you running on 11.1 or 11.0.1?  I've done builds on 11.0.1 but haven't updated to 11.1 yet

**Comment by mobileoverlord** [comment]
Looks like I am on 11.1

**Comment by mobileoverlord** [comment]
Are you using packages from homebrew native at all for your build?

**Comment by galak** [comment]
I'm using homebrew for the build.

```
          brew install autoconf automake bash binutils gawk gnu-sed gnu-tar help2man ncurses
```

You'll want to do:

```
            export PATH="$PATH:/usr/local/opt/binutils/bin"
            export CPPFLAGS="-I/usr/local/opt/ncurses/include -I/usr/local/opt/gettext/include"
            export LDFLAGS="-L/usr/local/opt/ncurses/lib -L/usr/local/opt/gettext/lib"
```

**Comment by galak** [comment]
> I'm using homebrew for the build.
> 
> ```
>           brew install autoconf automake bash binutils gawk gnu-sed gnu-tar help2man ncurses
> ```

I feel like on M1 there was another package I need to install, but I don't remember what it was.  It was obvious when the build fails.

**Pull request merged**
