### PR TITLE
gdb: fixes native build for musl (sgidefs.h availability)

### PR DESCRIPTION
**Pull request by kozyilmaz**
MIPS and musl libc based targets fail at native gdb due to missing sgidefs.h. gdb can be patched to include asm/sgidefs.h

```
$ ct-ng build
[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20170101.135808
[INFO ]  Building environment variables
[WARN ]  Directory '/home/loki/src' does not exist.
[WARN ]  Will not save downloaded tarballs to local storage.
[EXTRA]  Preparing working directories
[EXTRA]  Installing user-supplied crosstool-NG configuration
[EXTRA]  =================================================================
[EXTRA]  Dumping internal crosstool-NG configuration
[EXTRA]    Building a toolchain for:
[EXTRA]      build  = x86_64-pc-linux-gnu
[EXTRA]      host   = x86_64-pc-linux-gnu
[EXTRA]      target = mipsel-mt762x-linux-musl
[EXTRA]  Dumping internal crosstool-NG configuration: done in 0.09s (at 00:02)
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[EXTRA]    Retrieving 'musl-1.1.15'
[INFO ]  Retrieving needed toolchain components' tarballs: done in 6.02s (at 00:08)
[INFO ]  =================================================================
[INFO ]  Extracting and patching toolchain components
[EXTRA]    Extracting 'linux-4.8.8'
[EXTRA]    Patching 'linux-4.8.8'
[EXTRA]    Extracting 'gmp-6.1.0'
[EXTRA]    Patching 'gmp-6.1.0'
[EXTRA]    Extracting 'mpfr-3.1.3'
[EXTRA]    Patching 'mpfr-3.1.3'
[EXTRA]    Extracting 'isl-0.14'
[EXTRA]    Patching 'isl-0.14'
[EXTRA]    Extracting 'mpc-1.0.3'
[EXTRA]    Patching 'mpc-1.0.3'
[EXTRA]    Extracting 'expat-2.1.0'
[EXTRA]    Patching 'expat-2.1.0'
[EXTRA]    Extracting 'ncurses-6.0'
[EXTRA]    Patching 'ncurses-6.0'
[EXTRA]    Extracting 'binutils-2.26'
[EXTRA]    Patching 'binutils-2.26'
[EXTRA]    Extracting 'gcc-6.2.0'
[EXTRA]    Patching 'gcc-6.2.0'
[EXTRA]    Extracting 'musl-1.1.15'
[EXTRA]    Patching 'musl-1.1.15'
[EXTRA]    Extracting 'gdb-7.11'
[EXTRA]    Patching 'gdb-7.11'
[INFO ]  Extracting and patching toolchain components: done in 65.04s (at 01:13)
[INFO ]  =================================================================
[INFO ]  Installing ncurses for build
[EXTRA]    Configuring ncurses
[EXTRA]    Building ncurses
[EXTRA]    Installing ncurses
[INFO ]  Installing ncurses for build: done in 24.80s (at 01:38)
[INFO ]  =================================================================
[INFO ]  Installing GMP for host
[EXTRA]    Configuring GMP
[EXTRA]    Building GMP
[EXTRA]    Installing GMP
[INFO ]  Installing GMP for host: done in 42.77s (at 02:21)
[INFO ]  =================================================================
[INFO ]  Installing MPFR for host
[EXTRA]    Configuring MPFR
[EXTRA]    Building MPFR
[EXTRA]    Installing MPFR
[INFO ]  Installing MPFR for host: done in 21.56s (at 02:42)
[INFO ]  =================================================================
[INFO ]  Installing ISL for host
[EXTRA]    Configuring ISL
[EXTRA]    Building ISL
[EXTRA]    Installing ISL
[INFO ]  Installing ISL for host: done in 19.06s (at 03:01)
[INFO ]  =================================================================
[INFO ]  Installing MPC for host
[EXTRA]    Configuring MPC
[EXTRA]    Building MPC
[EXTRA]    Installing MPC
[INFO ]  Installing MPC for host: done in 10.90s (at 03:12)
[INFO ]  =================================================================
[INFO ]  Installing expat for host
[EXTRA]    Configuring expat
[EXTRA]    Building expat
[EXTRA]    Installing expat
[INFO ]  Installing expat for host: done in 6.94s (at 03:19)
[INFO ]  =================================================================
[INFO ]  Installing binutils for host
[EXTRA]    Configuring binutils
[EXTRA]    Prepare binutils for static build
[EXTRA]    Building binutils
[EXTRA]    Installing binutils
[INFO ]  Installing binutils for host: done in 55.93s (at 04:15)
[INFO ]  =================================================================
[INFO ]  Installing pass-1 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[EXTRA]    Installing gcc
[EXTRA]    Housekeeping for core gcc compiler
[EXTRA]    gcc default flags: '-EL'
[EXTRA]    gcc configured with these multilibs (including the default):
[EXTRA]       '' --> lib (gcc)   lib (os)
[INFO ]  Installing pass-1 core C gcc compiler: done in 210.06s (at 07:45)
[INFO ]  =================================================================
[INFO ]  Installing kernel headers
[EXTRA]    Installing kernel headers
[EXTRA]    Checking installed headers
[INFO ]  Installing kernel headers: done in 11.53s (at 07:57)
[INFO ]  =================================================================
[INFO ]  Installing C library headers & start files
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Installing C library headers
[EXTRA]      Building C library start files
[EXTRA]      Installing C library start files
[INFO ]    Building for multilib 1/1: '': done in 2.68s (at 07:59)
[INFO ]  Installing C library headers & start files: done in 2.76s (at 07:59)
[INFO ]  =================================================================
[INFO ]  Installing pass-2 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[EXTRA]    Installing gcc
[EXTRA]    Housekeeping for core gcc compiler
[EXTRA]    gcc default flags: '-EL'
[EXTRA]    gcc configured with these multilibs (including the default):
[EXTRA]       '' --> lib (gcc)   lib (os)
[INFO ]  Installing pass-2 core C gcc compiler: done in 253.85s (at 12:13)
[INFO ]  =================================================================
[INFO ]  Installing C library
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Cleaning up start files
[EXTRA]      Building C library
[EXTRA]      Installing C library
[INFO ]    Building for multilib 1/1: '': done in 18.34s (at 12:32)
[INFO ]  Installing C library: done in 18.41s (at 12:32)
[INFO ]  =================================================================
[INFO ]  Installing final gcc compiler
[EXTRA]    Configuring final gcc compiler
[EXTRA]    Building final gcc compiler
[EXTRA]    Installing final gcc compiler
[EXTRA]    Housekeeping for final gcc compiler
[EXTRA]    gcc default flags: '-EL'
[EXTRA]    gcc configured with these multilibs (including the default):
[EXTRA]       '' --> lib (gcc)   lib (os)
[INFO ]  Installing final gcc compiler: done in 263.55s (at 16:55)
[INFO ]  =================================================================
[INFO ]  Installing expat for target
[EXTRA]    Configuring expat
[EXTRA]    Building expat
[EXTRA]    Installing expat
[INFO ]  Installing expat for target: done in 5.93s (at 17:01)
[INFO ]  =================================================================
[INFO ]  Installing ncurses for target
[EXTRA]    Configuring ncurses
[EXTRA]    Building ncurses
[EXTRA]    Installing ncurses
[INFO ]  Installing ncurses for target: done in 25.52s (at 17:27)
[INFO ]  =================================================================
[INFO ]  Installing cross-gdb
[EXTRA]    Configuring cross-gdb
[EXTRA]    Building cross-gdb
[EXTRA]    Installing cross-gdb
[EXTRA]    Installing '.gdbinit' template
[INFO ]  Installing cross-gdb: done in 134.74s (at 19:42)
[INFO ]  =================================================================
[INFO ]  Installing native gdb
[EXTRA]    Configuring native gdb
[EXTRA]    Building native gdb
[ERROR]    /opt/ct/build/.build/src/gdb-7.11/gdb/mips-linux-nat.c:34:21: fatal error: sgidefs.h: No such file or directory
[ERROR]    make[3]: *** [mips-linux-nat.o] Error 1
[ERROR]    make[3]: *** Waiting for unfinished jobs....
[ERROR]    make[2]: *** [all-gdb] Error 2
[ERROR]    make[1]: *** [all] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing native gdb'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@259]
[ERROR]  >>        called from: do_debug_gdb_build[scripts/build/debug/300-gdb.sh@252]
[ERROR]  >>        called from: do_debug[scripts/build/debug.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@628]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/opt/ct/share/doc/crosstool-ng/crosstool-ng-1.22.0-388-gb7695d8/B - Known issues.txt'
[ERROR]   
[ERROR]  (elapsed: 21:27.77)
[21:28] / /opt/ct/bin/ct-ng:152: recipe for target 'build' failed
make: *** [build] Error 2
```

### CODE REVIEW

**Comment by kozyilmaz** [comment]
There seems to be a 50 min time limit for test builds (Travis CI) two failures are a result of it.

**Comment by stilor** [comment]
1. Has this patch been submitted upstream?
2. We now have 7.12 which seems to be affected, too - can you apply the patch to both 7.11/7.12?

**Comment by kozyilmaz** [comment]
This patch is not in upstream yet!
I added the same patch for gdb 7.12

**Comment by kozyilmaz** [comment]
Getting another problem:

```
$ /opt/ct/bin/ct-ng build
[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20170117.143407
[INFO ]  Building environment variables
[WARN ]  Directory '/home/loki/src' does not exist.
[WARN ]  Will not save downloaded tarballs to local storage.
[EXTRA]  Preparing working directories
[EXTRA]  Installing user-supplied crosstool-NG configuration
[EXTRA]  =================================================================
[EXTRA]  Dumping internal crosstool-NG configuration
[EXTRA]    Building a toolchain for:
[EXTRA]      build  = x86_64-pc-linux-gnu
[EXTRA]      host   = x86_64-pc-linux-gnu
[EXTRA]      target = mipsel-mt762x-linux-musl
[EXTRA]  Dumping internal crosstool-NG configuration: done in 0.08s (at 00:01)
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[EXTRA]    Retrieving 'linux-4.8.8'
[EXTRA]    Retrieving 'gmp-6.1.2'
[EXTRA]    Retrieving 'mpfr-3.1.5'
[EXTRA]    Retrieving 'isl-0.16.1'
[EXTRA]    Retrieving 'mpc-1.0.3'
[EXTRA]    Retrieving 'expat-2.2.0'
[EXTRA]    Retrieving 'ncurses-6.0'
[EXTRA]    Retrieving 'libiconv-1.14'
[EXTRA]    Retrieving 'gettext-0.19.7'
[EXTRA]    Retrieving 'binutils-2.27'
[EXTRA]    Retrieving 'gcc-6.3.0'
[EXTRA]    Retrieving 'musl-1.1.16'
[EXTRA]    Retrieving 'gdb-7.12'
[INFO ]  Retrieving needed toolchain components' tarballs: done in 502.96s (at 08:24)
[INFO ]  =================================================================
[INFO ]  Extracting and patching toolchain components
[EXTRA]    Extracting 'linux-4.8.8'
[EXTRA]    Patching 'linux-4.8.8'
[EXTRA]    Extracting 'gmp-6.1.2'
[EXTRA]    Patching 'gmp-6.1.2'
[EXTRA]    Extracting 'mpfr-3.1.5'
[EXTRA]    Patching 'mpfr-3.1.5'
[EXTRA]    Extracting 'isl-0.16.1'
[EXTRA]    Patching 'isl-0.16.1'
[EXTRA]    Extracting 'mpc-1.0.3'
[EXTRA]    Patching 'mpc-1.0.3'
[EXTRA]    Extracting 'expat-2.2.0'
[EXTRA]    Patching 'expat-2.2.0'
[EXTRA]    Extracting 'ncurses-6.0'
[EXTRA]    Patching 'ncurses-6.0'
[EXTRA]    Extracting 'libiconv-1.14'
[EXTRA]    Patching 'libiconv-1.14'
[EXTRA]    Extracting 'gettext-0.19.7'
[EXTRA]    Patching 'gettext-0.19.7'
[EXTRA]    Extracting 'binutils-2.27'
[EXTRA]    Patching 'binutils-2.27'
[EXTRA]    Extracting 'gcc-6.3.0'
[EXTRA]    Patching 'gcc-6.3.0'
[EXTRA]    Extracting 'musl-1.1.16'
[EXTRA]    Patching 'musl-1.1.16'
[EXTRA]    Extracting 'gdb-7.12'
[EXTRA]    Patching 'gdb-7.12'
[INFO ]  Extracting and patching toolchain components: done in 53.36s (at 09:17)
[INFO ]  =================================================================
[INFO ]  Installing ncurses for build
[EXTRA]    Configuring ncurses
[EXTRA]    Building ncurses
[EXTRA]    Installing ncurses
[INFO ]  Installing ncurses for build: done in 16.90s (at 09:34)
[INFO ]  =================================================================
[INFO ]  Installing GMP for host
[EXTRA]    Configuring GMP
[EXTRA]    Building GMP
[EXTRA]    Installing GMP
[INFO ]  Installing GMP for host: done in 38.45s (at 10:13)
[INFO ]  =================================================================
[INFO ]  Installing MPFR for host
[EXTRA]    Configuring MPFR
[EXTRA]    Building MPFR
[EXTRA]    Installing MPFR
[INFO ]  Installing MPFR for host: done in 21.49s (at 10:34)
[INFO ]  =================================================================
[INFO ]  Installing ISL for host
[EXTRA]    Configuring ISL
[EXTRA]    Building ISL
[EXTRA]    Installing ISL
[INFO ]  Installing ISL for host: done in 24.08s (at 10:58)
[INFO ]  =================================================================
[INFO ]  Installing MPC for host
[EXTRA]    Configuring MPC
[EXTRA]    Building MPC
[EXTRA]    Installing MPC
[INFO ]  Installing MPC for host: done in 10.91s (at 11:09)
[INFO ]  =================================================================
[INFO ]  Installing expat for host
[EXTRA]    Configuring expat
[EXTRA]    Building expat
[EXTRA]    Installing expat
[INFO ]  Installing expat for host: done in 5.69s (at 11:15)
[INFO ]  =================================================================
[INFO ]  Installing libiconv for host
[EXTRA]    Configuring libiconv
[EXTRA]    Building libiconv
[EXTRA]    Installing libiconv
[INFO ]  Installing libiconv for host: done in 236.70s (at 15:12)
[INFO ]  =================================================================
[INFO ]  Installing gettext for host
[EXTRA]    Configuring gettext
[EXTRA]    Building gettext
[EXTRA]    Installing gettext
[INFO ]  Installing gettext for host: done in 169.26s (at 18:01)
[INFO ]  =================================================================
[INFO ]  Installing binutils for host
[EXTRA]    Configuring binutils
[EXTRA]    Prepare binutils for static build
[EXTRA]    Building binutils
[EXTRA]    Installing binutils
[INFO ]  Installing binutils for host: done in 58.26s (at 18:59)
[INFO ]  =================================================================
[INFO ]  Installing pass-1 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[EXTRA]    Installing gcc
[EXTRA]    Housekeeping for core gcc compiler
[EXTRA]    gcc default flags: '-EL'
[EXTRA]    gcc configured with these multilibs (including the default):
[EXTRA]       '' --> lib (gcc)   lib (os)
[INFO ]  Installing pass-1 core C gcc compiler: done in 277.70s (at 23:37)
[INFO ]  =================================================================
[INFO ]  Installing kernel headers
[EXTRA]    Installing kernel headers
[EXTRA]    Checking installed headers
[INFO ]  Installing kernel headers: done in 9.32s (at 23:46)
[INFO ]  =================================================================
[INFO ]  Installing C library headers & start files
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Installing C library headers
[EXTRA]      Building C library start files
[EXTRA]      Installing C library start files
[INFO ]    Building for multilib 1/1: '': done in 2.02s (at 23:48)
[INFO ]  Installing C library headers & start files: done in 2.08s (at 23:48)
[INFO ]  =================================================================
[INFO ]  Installing pass-2 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[EXTRA]    Installing gcc
[EXTRA]    Housekeeping for core gcc compiler
[EXTRA]    gcc default flags: '-EL'
[EXTRA]    gcc configured with these multilibs (including the default):
[EXTRA]       '' --> lib (gcc)   lib (os)
[INFO ]  Installing pass-2 core C gcc compiler: done in 339.00s (at 29:27)
[INFO ]  =================================================================
[INFO ]  Installing C library
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Cleaning up start files
[EXTRA]      Building C library
[EXTRA]      Installing C library
[INFO ]    Building for multilib 1/1: '': done in 30.30s (at 29:58)
[INFO ]  Installing C library: done in 30.37s (at 29:58)
[INFO ]  =================================================================
[INFO ]  Installing final gcc compiler
[EXTRA]    Configuring final gcc compiler
[EXTRA]    Building final gcc compiler
[EXTRA]    Installing final gcc compiler
[EXTRA]    Housekeeping for final gcc compiler
[EXTRA]    gcc default flags: '-EL'
[EXTRA]    gcc configured with these multilibs (including the default):
[EXTRA]       '' --> lib (gcc)   lib (os)
[INFO ]  Installing final gcc compiler: done in 346.84s (at 35:45)
[INFO ]  =================================================================
[INFO ]  Installing cross-gdb
[EXTRA]    Configuring cross-gdb
[EXTRA]    Building cross-gdb
[EXTRA]    Installing cross-gdb
[EXTRA]    Installing '.gdbinit' template
[INFO ]  Installing cross-gdb: done in 125.83s (at 37:51)
[INFO ]  =================================================================
[INFO ]  Installing gdbserver
[EXTRA]    Configuring gdbserver
[EXTRA]    Building gdbserver
[ERROR]    build-gnulib-gdbserver/import/string.h:549:38: error: ambiguating new declaration of 'void* rawmemchr(const void*, int)'
[ERROR]    build-gnulib-gdbserver/import/string.h:549:38: error: ambiguating new declaration of 'void* rawmemchr(const void*, int)'
[ERROR]    build-gnulib-gdbserver/import/string.h:549:38: error: ambiguating new declaration of 'void* rawmemchr(const void*, int)'
[ERROR]    make[1]: *** [agent.o] Error 1
[ERROR]    make[1]: *** Waiting for unfinished jobs....
[ERROR]    build-gnulib-gdbserver/import/string.h:549:38: error: ambiguating new declaration of 'void* rawmemchr(const void*, int)'
[ERROR]    make[1]: *** [regcache.o] Error 1
[ERROR]    make[1]: *** [inferiors.o] Error 1
[ERROR]    make[1]: *** [ax.o] Error 1
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing gdbserver'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@259]
[ERROR]  >>        called from: do_debug_gdb_build[scripts/build/debug/300-gdb.sh@332]
[ERROR]  >>        called from: do_debug[scripts/build/debug.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@666]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/opt/ct/share/doc/crosstool-ng/crosstool-ng-1.22.0-453-g2227f3a/B - Known issues.txt'
[ERROR]   
[ERROR]  (elapsed: 38:26.72)
[38:27] / /opt/ct/bin/ct-ng:152: recipe for target 'build' failed
make: *** [build] Error 2
loki@asgard:/opt/ct/build$ 
```

**Comment by stilor** [comment]
1. Please submit upstream. In the patch, there's a line 'Upstream: Pending', but I cannot find that patch in the GDB database.
2. Procedural: please add 'Signed-off-by' line to your commits.
3. Procedural: please rebase rather than merge when picking up the changes from master.
4. You haven't posted the .config you're using. I used the sample in ct-ng (mipsel-unknown-linux-gnu) and changed glibc into musl. While the original problem appeared, I didn't see any issues with the gdbserver - it built fine. I then encountered an issue with strace - presumably fixed by [1]. That patch also says 'Upstream: Pending', and I didn't see it submitted to strace either.

As you might've noticed, I really prefer to have patches reviewed/integrated upstream, so that we don't have to maintain them for new releases.

[1] http://lists.openembedded.org/pipermail/openembedded-core/2016-February/117340.html

**Comment by stilor** [comment]
This may have given you an idea why musl is marked experimental :)

**Comment by kozyilmaz** [comment]
I am not familiar with gdb upstreaming processing and I am not the original author of the patch too so I'll drop this pull request for now. I'll conform to your procedural requirements next time.

**Comment by stilor** [comment]
Well, there is nothing special about "gdb upstreaming" - just create a bug in their database and attach the patch. I guess I'll need to do that myself, then...

**Comment by stilor** [comment]
... and, I'd still be interested in seeing the .config you use - as I said, I wasn't able to reproduce your issue with 'ambiguating new declaration' while building the gdbserver.

**Comment by stilor** [comment]
Upstream: http://sourceware.org/bugzilla/show_bug.cgi?id=21070

**Comment by kozyilmaz** [comment]
Hi stilor;

I have a test config for some MediaTek chips

```
CT_LOCAL_TARBALLS_DIR="${HOME}/src"
CT_SAVE_TARBALLS=y
CT_STRIP_TARGET_TOOLCHAIN_EXECUTABLES=y
CT_LOG_EXTRA=y
CT_ARCH_ARCH="mips32r2"
CT_ARCH_TUNE="24kec"
CT_ARCH_LE=y
CT_ARCH_32=y
# CT_ARCH_64 is not set
CT_ARCH_FLOAT_SW=y
CT_TARGET_CFLAGS="-mdsp"
CT_ARCH_mips=y
CT_STATIC_TOOLCHAIN=y
CT_TARGET_VENDOR="mt762x"
CT_TARGET_ALIAS="mipsel-linux"
CT_KERNEL_linux=y
CT_CC_GCC_mips_llsc=y
CT_CC_GCC_mips_synci=y
CT_CC_GCC_mips_plt=y
CT_CC_LANG_CXX=n
CT_DEBUG_gdb=y
CT_GDB_CROSS=y
CT_GDB_CROSS_STATIC=y
CT_GDB_NATIVE=y
CT_GDB_NATIVE_STATIC=y
```

**Pull request closed without merging**
