### PR TITLE
Update GCC Linaro 4.9-2015.06 to 4.9-2016.02

### PR DESCRIPTION
**Pull request by holyangel**
Get us on the latest patch here for this release instead of ~8 months old.

### CODE REVIEW

**Comment by mcrapet** [comment]
I vote for this!

**Comment by bhundven** [comment]
Please save the samples with `ct-ng savedefconfig`, then type `ct-ng saveconfig`, results in the `samples` directory.
This will allow you to added the `reported.by` file, as well as a minimal config file. By having the minimal config file, it will work with newer versions of crosstool-ng with less work.

**Comment by bhundven** [comment]
Also, there are merge conflicts in this set of commits. Please fix them, and we'll review again.

**Comment by bhundven** [comment]
As well, your commit messages needs to be signed off:

```
Signed-off-by: Your Name <youremail@example.com>
```

I do this automatically by doing `git commit -s`.

I also recommend actually adding a commit message. Sometimes the commit title is enough (for instance with the samples. It's pretty self explanatory).

You can fix that with:
(assuming that you are in a clone of your tree, being `origin`)

```
# Setup your git client
git config --global user.name "Your Name"
git config --global user.email "youremail@example.com"
# Add the upstream tree
git remote add crosstool-ng https://github.com/crosstool-ng/crosstool-ng
# Fetch all remotes
git fetch --all
# Check out master and merge upstream master to it
git checkout master
git merge crosstool-ng/master
# Check out the branch you did your work in (unless it was master)
git checkout [your_topic_branch]
# Rebase your topic branch with upstream master.
git rebase --ignore-whitespace crosstool-ng/master
<fix conflicts>
# Do an interactive rebase to reword the commit messages
git rebase -i [commit-sha]^
<replace 'pick' with 'reword' on commits>
<add sign-off>
# Push your new branches
git push origin master
git push --force origin [your_topic_branch]
```

Where `[commit-sha]^` might look like `2b8a386^`

This pull request will be updated, but some of the comments might disappear.

**Comment by holyangel** [comment]
Ah sorry about that. Didn't meant to create another request for these last two as they were just for me. Up to you to keep either. Thanks very much for the info, will do so, and will be more careful.

**Pull request closed without merging**
