### PR TITLE
populate: Fix undefined awk

### PR DESCRIPTION
**Pull request by jmlemetayer**
Fix minor issue introduced by 6f8e89cb5ca061e899bf3feaaf3fecf30d366c3e

### CODE REVIEW

**Comment by pankajbansal3073** [comment]
This change will fix this issue "populate command not working #394"( https://github.com/crosstool-ng/crosstool-ng/issues/394 )

**Comment by alexk-motu** [comment]
Is there any plan for merging this into master and getting it into an official release?

**Comment by bhundven** [comment]
Yes. I'm just behind on everything.

**Comment by alexk-motu** [comment]
Sorry to hear that! I don't mean to attack or hassle you, just wanted to make sure this was on someone's radar.

**Comment by bhundven** [comment]
Thanks!

**Pull request merged**
