### PR TITLE
Xtensa fixes

### PR DESCRIPTION
**Pull request by jcmvbkbc**
Hi Bryan,

please merge the following two xtensa-specific patches that fix build of little-endian uClibc-based toolchain and arrange for better code generation for target libraries.

### CODE REVIEW

**Comment by bhundven** [comment]
@jcmvbkbc Could you update this branch? I'd like to get this merged soon.

**Comment by jcmvbkbc** [comment]
> Could you update this branch? I'd like to get this merged soon.

@bhundven updated to the current master + added 4 more fixes for gcc 5.x and 6.x: one ICE (6.x), two libgcc build fixes (5.x and 6.x) and one libgcc correctness fix (5.x).

> should this choice (LE v. BE) be reflected in the configuration's tuple?

@stilor It's not really a choice: selected processor configuration determines endianness, the toolchain can not be built with different endianness. There's no strict rule here. I usually mention processor name in the tuple.

**Comment by stilor** [comment]
@jcmvbkbc You mean, in the vendor string like we do with certain PowerPC samples? Maybe update this sample with specific CPU name then?

**Comment by jcmvbkbc** [comment]
@stilor Done.

**Pull request merged**
