### PR TITLE
binutils-oracle: Update source patch location for ol8

### PR DESCRIPTION
**Pull request by gemaq**
Due to a new commit oracle binutils branch an update location for
patches is required. This patch disabled debug information for
glibc too.

### CODE REVIEW

**Comment by gemaq** [comment]
@cpackham I saw some checks that are trigger after submitting a pull request like this: toolchains / build (ubuntu-latest, riscv64-unknown-elf). What are the prerequisites to have a  `toolchains / build (ubuntu-latest, {aarch64-ol8u6-linux-gnu,x86_64-ol8u6-linux-gnu, aarch64-ol7u9-linux-gnu, arm-ol7u9-linux-gnueabi{,hf}}`), if you think that is a good idea, I would like to work on this.

**Comment by cpackham** [comment]
> @cpackham I saw some checks that are trigger after submitting a pull request like this: toolchains / build (ubuntu-latest, riscv64-unknown-elf). What are the prerequisites to have a `toolchains / build (ubuntu-latest, {aarch64-ol8u6-linux-gnu,x86_64-ol8u6-linux-gnu, aarch64-ol7u9-linux-gnu, arm-ol7u9-linux-gnueabi{,hf}}`), if you think that is a good idea, I would like to work on this.

We've never had hard prerequisites for the CI builds. Back when we were using travis-ci it was anything that could build in under 50 minutes but that was pushing it for most configs. When github actions came along I just tried to get at least one of each architecture and tried to spread out to make sure we did at least one of each libc and maybe some of the more popular targets (arm and aarch64). I thought github might complain that we're abusing the free tier at some point but they haven't said anything yet.

I think the fact that you're interested in those specific configs is more that enough reason to add them (it's certainly more than we have for most of the configs we're building).

**Review by cpackham — APPROVED** [review]
Try to remember to add your Signed-off-by line to your commits.

**Comment by gemaq** [comment]
> Try to remember to add your Signed-off-by line to your commits.

Ohh, apologize, I will keep in mind.

**Comment by gemaq** [comment]
> > @cpackham I saw some checks that are trigger after submitting a pull request like this: toolchains / build (ubuntu-latest, riscv64-unknown-elf). What are the prerequisites to have a `toolchains / build (ubuntu-latest, {aarch64-ol8u6-linux-gnu,x86_64-ol8u6-linux-gnu, aarch64-ol7u9-linux-gnu, arm-ol7u9-linux-gnueabi{,hf}}`), if you think that is a good idea, I would like to work on this.
> 
> We've never had hard prerequisites for the CI builds. Back when we were using travis-ci it was anything that could build in under 50 minutes but that was pushing it for most configs. When github actions came along I just tried to get at least one of each architecture and tried to spread out to make sure we did at least one of each libc and maybe some of the more popular targets (arm and aarch64). I thought github might complain that we're abusing the free tier at some point but they haven't said anything yet.

Thanks for the explanations.
 
> I think the fact that you're interested in those specific configs is more that enough reason to add them (it's certainly more than we have for most of the configs we're building).

Yes, I just want to extend the environment where it is tested to looks for regressions. Thanks!

**Pull request merged**
