### PR TITLE
Sync kconfig files with upstream 4.15

### PR DESCRIPTION
**Pull request by bhundven**
Last updated with 4.9-rc7.
This commit introduces the following upstream changes:

9059a3493efe kconfig: fix relational operators for bool and tristate symbols
88127dae6ed9 kconfig/symbol.c: use correct pointer type argument for sizeof
b24413180f56 License cleanup: add SPDX GPL-2.0 license identifier to files with no license
bb3290d91695 Remove gperf usage from toolchain
ad8181060788 kconfig: fix sparse warnings in nconfig
ff85a1a80e00 kconfig: Check for libncurses before menuconfig
9be3213b14d4 gconfig: remove misleading parentheses around a condition
83c3a1bad224 xconfig: fix missing suboption and help panels on first run
e039303ff71a xconfig: fix 'Show Debug' functionality
79e51b5c2dee kconfig/nconf: Fix hang when editing symbol with a long prompt
0eb47346968f Scripts: kconfig: nconf: fix _GNU_SOURCE redefined warning
237e3ad0f195 Kconfig: Introduce the "imply" keyword

Signed-off-by: Bryan Hundven <bryanhundven@gmail.com>

### CODE REVIEW

**Comment by bhundven** [comment]
I believe @yann-morin-1998 had similar ideas. I personally agree and think it's a great idea.
I'm guessing Yann does not maintain kconfig anymore:
```KCONFIG
L:	linux-kbuild@vger.kernel.org
S:	Orphan
F:	Documentation/kbuild/kconfig-language.txt
F:	scripts/kconfig/```

**Comment by bhundven** [comment]
would the kconfig project be a submodule?

**Comment by stilor** [comment]
Likely, yes, but it can also be "synced" by just copying the stuff over once in a while - if you think that'd be better.

Re Yann: that's bad, because I also wanted to submit some kconfig changes back to Linux. One thing is, we somewhat abuse "modules" semantic for tri-state - our "module" is really "auto". The difference is that "modularity" concept is inherited through dependencies - but "auto" setting, not necessarily so. That, and being able to separate project-specific stuff into separate files would ease maintaining the kconfig in projects that use it.

**Comment by bhundven** [comment]
Looks like the builds timed out :(

**Pull request merged**
