### PR TITLE
gcc/13.2.0: Add patch with fixes for m68k soft float code

### PR DESCRIPTION
**Pull request by keith-packard**
Here's a patch I've sent upstream which fixes a range of floating point bugs in libgcc.

### CODE REVIEW

**Review by cpackham — APPROVED** [review]
Thanks @keith-packard looks great.

**Comment by keith-packard** [comment]
> Thanks @keith-packard looks great.

I'm just finishing up testing these in picolibc CI -- I'm hoping the current run will succeed (picolibc CI runs are taking hours at this point, we have plans to improve that).

There are still pretty significant gaps in the 80-bit float code, but I stopped when picolibc CI stopped breaking ...

**Comment by keith-packard** [comment]
oh, is there some reason the m68k-unknown-elf sample config doesn't enable multilib support? Seems kinda necessary for any embedded uses I can imagine.

**Comment by cpackham** [comment]
> oh, is there some reason the m68k-unknown-elf sample config doesn't enable multilib support? Seems kinda necessary for any embedded uses I can imagine.

Not that I'm aware of. That sample is fairly old and multilib has always been considered a bit fragile. I don't have any objections to enabling it (after the 1.26.0 release).

**Comment by cpackham** [comment]
Just noticed our CI builds don't cover m68k. I'll do one manually as well

**Comment by keith-packard** [comment]
> Just noticed our CI builds don't cover m68k. I'll do one manually as well

If you want to run the picolibc test suite with the resulting toolchain (which I'm doing happily), you'll need a patched version of qemu as well. Speaking of which, I wonder if crosstool-ng should offer to include qemu as a tool in the toolchain? I know I need a matching qemu for every compiler ...

https://github.com/keith-packard/qemu/tree/m68k-mul2

**Pull request merged**
