### PR TITLE
Multilib

### PR DESCRIPTION
**Pull request by mingwandroid**
Here we go!

### CODE REVIEW

**Comment by trisk** [comment]
So I tried the unmodified changes (aside from removal of trailing whitespace in config/target.in) and the toolchain built fine. The resulting sysroot has {lib,usr/lib} containing 32-bit objects, and {lib64,usr/lib64} for 64-bit objects. However, when I tried to use the g++ (with C++ buildroot packages), it fails when implicitly linking libstdc++:

```
x86_64-unknown-linux-gnu-g++: error: /ws/mistifyio/mistify-os/toolchain/variations/master/x86_64-unknown-linux-gnu/lib/../lib64/libstdc++.so: No such file or directory
```
lib64/libstdc++.so.6 and lib64/libstdc++.so.6.0.20 do exist, but the lib64/libstdc++.so symlink is missing.

lib/libstdc++.so also exists, but is the 32-bit version:
```
/ws/mistifyio/mistify-os/toolchain/variations/master/x86_64-unknown-linux-gnu/lib/libstdc++.so.6.0.20: ELF 32-bit LSB shared object, Intel 80386, version 1 (GNU/Linux), dynamically linked, not stripped
```

**Comment by mingwandroid** [comment]
Thanks! I will look into this on Monday.

**Comment by mingwandroid** [comment]
I'm not seeing this, for me:

```
$ find /e/d/is -name "*libstdc++*" -exec ls -l {} \;
lrwxrwxrwx 1 ray users 19 Jun 21 23:27 /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib64/libstdc++.so.6 -> libstdc++.so.6.0.20
-rw-r--r-- 1 ray users 11693032 Jun 21 23:27 /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib64/libstdc++.a
-rw-r--r-- 1 ray users 2332 Jun 21 23:27 /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib64/libstdc++.so.6.0.20-gdb.py
-rwxr-xr-x 1 ray users 4760832 Jun 21 23:27 /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib64/libstdc++.so.6.0.20
-rwxr-xr-x 1 ray users 987 Jun 21 23:27 /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib64/libstdc++.la
lrwxrwxrwx 1 ray users 19 Jun 21 23:27 /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib/libstdc++.so -> libstdc++.so.6.0.20
lrwxrwxrwx 1 ray users 19 Jun 21 23:27 /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib/libstdc++.so.6 -> libstdc++.so.6.0.20
-rw-r--r-- 1 ray users 7170608 Jun 21 23:27 /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib/libstdc++.a
-rw-r--r-- 1 ray users 2330 Jun 21 23:27 /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib/libstdc++.so.6.0.20-gdb.py
-rwxr-xr-x 1 ray users 3857488 Jun 21 23:27 /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib/libstdc++.so.6.0.20
-rwxr-xr-x 1 ray users 985 Jun 21 23:27 /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib/libstdc++.la
```

and:

```
$ file /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib64/libstdc++.so.6.0.20
/e/d/is/x86_64-unknown-linux-gnu/sysroot/lib64/libstdc++.so.6.0.20: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, not stripped
$ file /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib/libstdc++.so.6.0.20
/e/d/is/x86_64-unknown-linux-gnu/sysroot/lib/libstdc++.so.6.0.20: ELF 32-bit LSB shared object, Intel 80386, version 1 (GNU/Linux), dynamically linked, not stripped
```

usage:

```
$ /e/d/is/bin/x86_64-unknown-linux-gnu-g++ hello-world.cpp -std=gnu++11 -m32
$ ./a.out 
Hello World! sizeof(void*)=4
$ /e/d/is/bin/x86_64-unknown-linux-gnu-g++ hello-world.cpp -std=gnu++11 -m64
$ ./a.out 
Hello World! sizeof(void*)=8
```

Can you post your .config and build log somewhere? Admittedly, my build script merged about 8 or 9 feature branches that I'm currently working on, but I don't *think* that will be the cause of this issue. Tomorrow I will do a build with just the multilib patches.

**Comment by trisk** [comment]
> I'm not seeing this, for me:
> 
> $ find /e/d/is -name "*libstdc++*" -exec ls -l {} \;
> lrwxrwxrwx 1 ray users 19 Jun 21 23:27 /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib64/libstdc++.so.6 -> libstdc++.so.6.0.20
> -rw-r--r-- 1 ray users 11693032 Jun 21 23:27 /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib64/libstdc++.a
> -rw-r--r-- 1 ray users 2332 Jun 21 23:27 /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib64/libstdc++.so.6.0.20-gdb.py
> -rwxr-xr-x 1 ray users 4760832 Jun 21 23:27 /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib64/libstdc++.so.6.0.20
> -rwxr-xr-x 1 ray users 987 Jun 21 23:27 /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib64/libstdc++.la
> lrwxrwxrwx 1 ray users 19 Jun 21 23:27 /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib/libstdc++.so -> libstdc++.so.6.0.20
> lrwxrwxrwx 1 ray users 19 Jun 21 23:27 /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib/libstdc++.so.6 -> libstdc++.so.6.0.20
> -rw-r--r-- 1 ray users 7170608 Jun 21 23:27 /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib/libstdc++.a
> -rw-r--r-- 1 ray users 2330 Jun 21 23:27 /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib/libstdc++.so.6.0.20-gdb.py
> -rwxr-xr-x 1 ray users 3857488 Jun 21 23:27 /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib/libstdc++.so.6.0.20
> -rwxr-xr-x 1 ray users 985 Jun 21 23:27 /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib/libstdc++.la
> and:
> 
> $ file /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib64/libstdc++.so.6.0.20
> /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib64/libstdc++.so.6.0.20: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, not stripped
> $ file /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib/libstdc++.so.6.0.20
> /e/d/is/x86_64-unknown-linux-gnu/sysroot/lib/libstdc++.so.6.0.20: ELF 32-bit LSB shared object, Intel 80386, version 1 (GNU/Linux), dynamically linked, not stripped

lib/libstdc++.so is present, but lib64/libstdc++.so symlink is also absent in your output. This is consistent with my sysroot contents (which include lib64/libstdc++.so.6, lib64/libstdc++.so.6.0.20, and lib64/libstdc++.la). My failure occurs in the buildroot package for pcre. pcre's build system uses libtool, so it's possible this failure isn't an implicit -lstdc++ (although why it would explicitly search for libstdc++, I don't know). FWIW lib64/libstdc++.la has: `library_names='libstdc++.so.6.0.20 libstdc++.so.6 libstdc++.so'`and `libdir='/ws/mistifyio/mistify-os/toolchain/variations/master/x86_64-unknown-linux-gnu/lib/../lib64'`

When I use x86_64-unknown-linux-gnu-g++ to compile and link a hello world program, I see failed accessed to lib64/libstdc++.so in a trace, and the resulting binary is linked with libstdc++.a!
```
$ /ws/mistifyio/mistify-os/toolchain/variations/master/bin/x86_64-unknown-linux-gnu-g++ test.cpp
$ objdump -x a.out | grep NEEDED
  NEEDED               libm.so.6
  NEEDED               libgcc_s.so.1
  NEEDED               libc.so.6
  NEEDED               ld-linux-x86-64.so.2
$ ls -l a.out
-rwxr-xr-x 1 trisk staff 3171472 Jun 21 21:46 a.out
```

**Comment by mingwandroid** [comment]
Updating with latest progress, not a solution as such. I *think* there's a race condition. I've added line numbers to the log:

````
268859 :: [ALL  ]    test -z "/e/d/is/x86_64-unknown-linux-gnu/lib/../lib64" || /usr/bin/mkdir -p "/e/d/is/x86_64-unknown-linux-gnu/lib/../lib64"
..
269401 :: [ALL  ]    libtool: install: (cd /e/d/is/x86_64-unknown-linux-gnu/lib/../lib64 && { ln -s -f libstdc++.so.6.0.20 libstdc++.so.6 || { rm -f libstdc++.so.6 && ln -s libstdc++.so.6.0.20 libstdc++.so.6; }; })
269402 :: [ALL  ]    ../libtool: line 1132: cd: /e/d/is/x86_64-unknown-linux-gnu/lib/../lib64: No such file or directory
269403 :: [ALL  ]    libtool: install: (cd /e/d/is/x86_64-unknown-linux-gnu/lib/../lib64 && { ln -s -f libstdc++.so.6.0.20 libstdc++.so || { rm -f libstdc++.so && ln -s libstdc++.so.6.0.20 libstdc++.so; }; })
269404 :: [ALL  ]    ../libtool: line 1132: cd: /e/d/is/x86_64-unknown-linux-gnu/lib/../lib64: No such file or directory
..
269763 :: [ALL  ]    test -z "/e/d/is/x86_64-unknown-linux-gnu/lib/../lib64" || /usr/bin/mkdir -p "/e/d/is/x86_64-unknown-linux-gnu/lib/../lib64"
````

.. if anyone can shed some light on this I'd appreciate it.

**Comment by bhundven** [comment]
@mingwandroid and @trisk, lets get together in IRC and talk about these two multilib patch sets. I've read both pull-requests, and changes. I just need more info.

**Comment by mingwandroid** [comment]
ok, when can people do this? I can do it now.

**Comment by mingwandroid** [comment]
Need to investigate this libstdc++ issue more. Hold fire on merging.

**Comment by bhundven** [comment]
@mingwandroid for multilib, should https://github.com/crosstool-ng/crosstool-ng/blob/b565e949d4d9eb695d026a963aa537f0d0992291/scripts/crosstool-NG.sh.in#L325 these symlinks be directories instead of symlinks?

**Comment by bhundven** [comment]
I meant line 342

**Comment by mingwandroid** [comment]
It's definitely die to the sysroot symlink that I get the failure. Thing is, making these folders is kind of gross. You don't even have compilers yet and only they know which multilib dirs they want. I'll bet it solved tonight.

BTW, can I setup Travis on my branch?

**Comment by bhundven** [comment]
This PR has been superseded by #383. Closing.

**Pull request closed without merging**
