### PR TITLE
Updates for GCC 13.1.0

### PR DESCRIPTION
**Pull request by cpackham**

### CODE REVIEW

**Review by bhundven — APPROVED** [review]

**Comment by heiher** [comment]
The build of glibc 2.36 failed when using gcc 13.1.

**Review by egtvedt — APPROVED** [review]

**Comment by cpackham** [comment]
Doesn't seem to like uclibc

```
[INFO ]  Installing final gcc compiler
[EXTRA]    Configuring final gcc compiler
[EXTRA]    Building final gcc compiler
[ERROR]    /home/ctng/crosstool-ng/.build/x86_64-multilib-linux-uclibc/src/gcc/libstdc++-v3/src/c++17/floating_from_chars.cc:1281:10: error: 'from_chars_strtod' was not declared in this scope
[ERROR]    make[6]: *** [Makefile:587: floating_from_chars.lo] Error 1
[ERROR]    make[6]: *** Waiting for unfinished jobs....
[ERROR]    make[5]: *** [Makefile:792: all-recursive] Error 1
[ERROR]    make[4]: *** [Makefile:576: all-recursive] Error 1
[ERROR]    make[3]: *** [Makefile:501: all] Error 2
[ERROR]    make[2]: *** [Makefile:12621: all-target-libstdc++-v3] Error 2
[ERROR]    make[1]: *** [Makefile:1042: all] Error 2
```

**Comment by cpackham** [comment]
I might split the first two changes into a new PR as it looks like there may be a bit more work required for GCC 13

**Comment by cpackham** [comment]
Looks like there might be some macOS/clang specific issues for riscv32 (and probable riscv64).

**Comment by jdknight** [comment]
https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=87c347c2897537a6aa391efbfc5ed00c625434fe

(if this helps, if it hasn't already been found yet)

**Pull request merged**
