### PR TITLE
First chunk of multilib changes for merging

### PR DESCRIPTION
**Pull request by stilor**
As indicated on IRC, first 10 commits were reviewed and ready to go.

### CODE REVIEW

**Comment by mingwandroid** [comment]
Good to see, I wish I had more time to help out than I do these days. crosstool-ng is an important project and your work on it is appreciated.

**Comment by bhundven** [comment]
@stilor Indeed! Your help is most appreciated! I know it has taken a long time to get even this far. I do really appreciate your help!

**Comment by bhundven** [comment]
Now we break all the other pull requests...

**Comment by stilor** [comment]
Not necessarily - unless they were touching scripts/functions, scripts/build/{arch,cc,libc}, they should be ok. While Yann reviews the next batch, please feel free to merge other PRs - I'll rebase when the next batch is ready to merge.

**Comment by djmott** [comment]
Thanks for all the work on this.

**Pull request merged**
