### PR TITLE
Loongarch support

### PR DESCRIPTION
**Pull request by jiegec**
This pr implements loongarch support for crosstool-ng. It requires GCC 12.1 and GDB 12.1 to work, so I cherry-picked the commits from @cpackham. A sample config for loongarch64-unknown-linux-gnu target is provided.

[GDB 12.1 News](https://www.sourceware.org/gdb/news/): 

```
New support for the following targets:
GNU/Linux/LoongArch loongarch*-*-linux*
```

[GCC 12 Release Notes](https://gcc.gnu.org/gcc-12/changes.html):

```
LoongArch
Support for the LoongArch architecture instruction set has been added.
The Loongson CPU codename LA464 and LoongArch 64-bit generic CPU codename loongarch64 are supported through the -march= and -mtune= options (GCC identifiers in parentheses).
Loongson LA464 core (la464).
LoongArch 64-bit generic core (loongarch64).
```

[Glibc 2.36 Release Notes](https://sourceware.org/pipermail/libc-announce/2022/000034.html):

```
* Support for LoongArch running on Linux has been added.  This port requires
  as least binutils 2.38, GCC 12, and Linux 5.19.  Currently only hard-float
  ABI is supported:

    - loongarch64-linux-gnu

  The LoongArch ABI is 64-bit little-endian.
```

[Linux 5.19 Release Notes](https://lore.kernel.org/lkml/CAHk-=wgrz5BBk=rCz7W28Fj_o02s0Xi0OEQ3H1uQgOdFvHgx0w@mail.gmail.com/T/#u)

```
In the diffstat, the loongarch updates stand out, as does another
batch of the networking sysctl READ_ONCE() annotations to make some of
the data race checker code happy.
```

Binutils 2.38 is incompatible with GCC 12.1 with regard to LoongArch abi settings. Binutils 2.39 is good.

Toolchain built:

```
loongarch64-unknown-linux-gnu-gcc (crosstool-NG 1.25.0.70_6f02e01) 12.1.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

GNU ld (crosstool-NG 1.25.0.70_6f02e01) 2.39
Copyright (C) 2022 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
GNU gdb (crosstool-NG 1.25.0.70_6f02e01) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
#define __GLIBC__       2
#define __GLIBC_MINOR__ 36
#define LINUX_VERSION_MAJOR 5
#define LINUX_VERSION_PATCHLEVEL 19
#define LINUX_VERSION_SUBLEVEL 0
```

### CODE REVIEW

**Comment by cpackham** [comment]
I'll hold off on approving the CI run until after the gdb/gcc changes are merged.

Probably worth adding the sample config to .github/workflows/continuous-integration-workflow.yml so it gets some build testing going forward.

**Comment by cpackham** [comment]
@jiegec I've just merged the GCC12 PR so you should be able to rebase on top of that.

Could you also split your commit in two. One adding the the architecture, the other adding the sample config (and add it to .github/workflows/continuous-integration-workflow.yml so we get at least one run through).

I don't want to merge (another) sample config depending on non-offical repos so that may have to wait until we see official upstream releases for binutils/glibc/linux with the Loongarch support (which sounds like it should be pretty soon). But there's no reason to hold up the architecture support.

**Comment by jiegec** [comment]
> @jiegec I've just merged the GCC12 PR so you should be able to rebase on top of that.
> 
> Could you also split your commit in two. One adding the the architecture, the other adding the sample config (and add it to .github/workflows/continuous-integration-workflow.yml so we get at least one run through).
> 
> I don't want to merge (another) sample config depending on non-offical repos so that may have to wait until we see official upstream releases for binutils/glibc/linux with the Loongarch support (which sounds like it should be pretty soon). But there's no reason to hold up the architecture support.

Fine, let's the the architecture support and wait until it's upstreamed.

**Comment by cpackham** [comment]
Looks like the macos-10.15 build isn't happy with the loongarch binutils. You can grab the build logs from [here](https://pipelines.actions.githubusercontent.com/serviceHosts/aa844ff1-eec5-4ae4-97a3-5f1a496a33e6/_apis/pipelines/1/runs/469/signedartifactscontent?artifactName=loongarch64-unknown-linux-gnu.macos-10.15.log&urlExpires=2022-05-19T21%3A59%3A49.1819617Z&urlSigningMethod=HMACV2&urlSignature=tczqJZPzMm0sKUh%2FGruMUj%2FwigMOFVQsOnkk46rbSgU%3D)

I had a quick glance and either there's some GNU specific thing in loongarch-parse.y that the BSD bison/flex doesn't like or possibly there's a missing dependency causing it to attempt to build `config/loongarch-parse.o` before `config/loongarch-parse.c` has been generated.

In terms of other review stuff could you make sure to add a reasonable commit message and include a `Signed-off-by:` line in the actual commits. You provided a pretty good write up in the PR itself but that only exists on github whereas commit messages go with the repository no matter where it's hosted.

**Comment by cpackham** [comment]
@jiegec I've just merged the PR for Linux 5.19 and glibc 2.36. If you rebase this on top of master the custom linux and glibc versions can drop out of the sample config.

Looks like binutils 2.39 is out. I'll do a PR for that shortly. Will that resolve the ABI issues you mentioned above?

**Comment by jiegec** [comment]
> @jiegec I've just merged the PR for Linux 5.19 and glibc 2.36. If you rebase this on top of master the custom linux and glibc versions can drop out of the sample config.
> 
> Looks like binutils 2.39 is out. I'll do a PR for that shortly. Will that resolve the ABI issues you mentioned above?

Thanks, let me test it.

**Review by cpackham — APPROVED** [review]
I wonder if the macOS issue is helped by either updating to macos12 or depending on host bison.

**Pull request merged**
