### PR TITLE
Fix zlib build on win32 near environments

### PR DESCRIPTION
**Pull request by QBos07**
Signed-off-by: Quentin Boswank <qubos@outlook.de>

### CODE REVIEW

**Comment by QBos07** [comment]
Fixes #2079

**Comment by QBos07** [comment]
We currently do not respect host/build tool suffixes for example `-win32` on `x86_64-w64-mingw32` but at least it builds now.

**Comment by cpackham** [comment]
@QBos07 thanks for the quick fix. I'll cherry-pick your fix into PR #2079

**Comment by cpackham** [comment]
Closed via #2079

**Pull request closed without merging**
