### PR TITLE
Pass flags for build

### PR DESCRIPTION
**Pull request by stilor**
First 3 commits are small clean-ups, last two are supposed to fix macos simple crosses.

### CODE REVIEW

**Comment by oxoocoffee** [comment]
Just pulled stilor:pass-flags-for-build. Starting new build

**Comment by stilor** [comment]
@oxoocoffee Another try.

**Comment by oxoocoffee** [comment]
Here it is :)
[output.zip](https://github.com/crosstool-ng/crosstool-ng/files/660914/output.zip)

**Comment by oxoocoffee** [comment]
Here it is
[build-cc-gcc-core-pass-1-intl-config.zip](https://github.com/crosstool-ng/crosstool-ng/files/661777/build-cc-gcc-core-pass-1-intl-config.zip)

**Comment by oxoocoffee** [comment]
Here is output file with current logs. Build, screen, build-cc-gcc-core-pass-1/intl/config.log and ct-ng config file used.

[output.zip](https://github.com/crosstool-ng/crosstool-ng/files/662072/output.zip)

**Comment by stilor** [comment]
Ok, it now correctly picked up libintl from our gettext. Judging by the warning messages ("clang: warning: -framework CoreFoundation: 'linker' input unused") it looks like this option is only needed for linker flags, not compiler flags.

It now fails while compiling a plugin for GCC - libtool, for some reason, decides to insert an extra `-framework` option before a path to libiberty.a. I might be reaching the limits of what I can do here without a macos environment... But let's try this:
- First, let's try to pass `-framework CoreFoundation` only in linker flags (not in compiler flags).
- Enable 'Debug crosstool-ng' -> 'Interactive shell on failed commands'
- If it fails in the same place, look at the last lines of the build log to find the failing libtool command (in the current build log it starts with `/usr/local/bin/bash ./libtool --tag=CC --tag=disable-static  --mode=link ...`)
- `cd lto-plugin`
- Cut&past the failing command, adding a `-x` after `bash`, i.e. `/usr/local/bin/bash -x ./libtool --tag=CC --tag=disable-static  --mode=link ...`)
- Save and attach the output of that command.

**Comment by oxoocoffee** [comment]
Here it is. Let me know any next steps :) Thank you

[output.zip](https://github.com/crosstool-ng/crosstool-ng/files/662625/output.zip)

**Comment by stilor** [comment]
In this case, it was GCC's mangling the libtool flags. I added a patch for it to leave `-framework` be, please try again :)

**Comment by oxoocoffee** [comment]
Should I clear both LDFLAGS/host in config? Or build it with -framework CoreFoundation?

**Comment by stilor** [comment]
Same as last time - `-framework CoreFoundation` in LDFLAGS for host.

**Comment by oxoocoffee** [comment]
So to save time I started with last config file :) Here is output

[output.zip](https://github.com/crosstool-ng/crosstool-ng/files/664885/output.zip)

**Comment by stilor** [comment]
Ok, this moves us a bit further. Now the pass-1 GCC builds successfully and it apparently works fine. But a bug in our `scripts/build/libc/glibc.sh` loses the LDFLAGS for build/host supplied by the user and hence, the build of glibc fails. I'll try to post a fix later today or tomorrow.

**Comment by stilor** [comment]
Ok, try again - same config.

**Comment by oxoocoffee** [comment]
Here it is :)
[outout.zip](https://github.com/crosstool-ng/crosstool-ng/files/666352/outout.zip)

**Comment by stilor** [comment]
One of the undefined symbols remained, hmm. It looks like that symbol, `_nl_msg_cat_cntr`, should've been provided by the libintl.a itself. It is there in my Linux build.

Can you post an output of `readelf -s .build/arm-cortexa9_neon-linux-gnueabihf/buildtools/lib/libintl.a`?

**Comment by oxoocoffee** [comment]
Here it is
[outout.zip](https://github.com/crosstool-ng/crosstool-ng/files/667110/outout.zip)

**Comment by stilor** [comment]
Ok, I didn't know macos wasn't using ELF. Can you do `nm .build/arm-cortexa9_neon-linux-gnueabihf/buildtools/lib/libintl.a` instead?

**Comment by oxoocoffee** [comment]
Here it is 
[libintl.nm.zip](https://github.com/crosstool-ng/crosstool-ng/files/667364/libintl.nm.zip)

**Comment by stilor** [comment]
Interesting, the symbol is there (in loadmsgcat.o), but somehow not picked up by linker. Please do:

`cd /Volumes/Yocto/crosstool-ng/.build/src/glibc-2.23/sunrpc`
`PATH=/Volumes/Yocto/crosstool-ng-output/x-tools/arm-cortexa9_neon-linux-gnueabihf/bin:/Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/buildtools/bin:/Volumes/Yocto/crosstool-ng/.build/tools/bin:$PATH`
`x86_64-build_apple-darwin16.3.0-gcc /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/cross-rpc_main.o /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/cross-rpc_hout.o /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/cross-rpc_cout.o /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/cross-rpc_parse.o /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/cross-rpc_scan.o /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/cross-rpc_util.o /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/cross-rpc_svcout.o /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/cross-rpc_clntout.o /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/cross-rpc_tblout.o /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/cross-rpc_sample.o -L/Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/buildtools/lib  -framework CoreFoundation -lintl -o /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/cross-rpcgen -Wl,-Map,linkmap.txt`

This should produce a `linkmap.txt` file in that directory; please attach it.

**Comment by oxoocoffee** [comment]
[command.zip](https://github.com/crosstool-ng/crosstool-ng/files/667649/command.zip)

**Comment by stilor** [comment]
So clang's linker does not have a -Map option (like GNU ld). I hate to say it, but I don't know what else to try: the symbol is in libintl.a (as evidenced by the nm output) but the linker fails with an unresolved reference to that symbol. You might need someone with MacOS experience here.

@bhundven, I suggest to integrate this branch - it has a few bugfixes that are not just for MacOS.

**Comment by oxoocoffee** [comment]
I will try -Wl,-map,output.map later tonight when I have access.

**Comment by oxoocoffee** [comment]
Ok I got now access to my machine all the time :) After reading man pages I see that it should be -map vs -Map. I did created simple main.c and did try to build it with x86_64-build_apple-darwin16.3.0-gcc -Wl,-map,linkmap.txt main.c and it created linkmap.txt.

Now following your instructions this does not produce linkmap.txt. I did search for this file in entire /Volume/Yocto/crosstool-ng/ and there is no such file produced. 

Looking at your above post looks like link file should be produced in /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/? or /Volumes/Yocto/crosstool-ng/.build/src/glibc-2.23/sunrpc/? Neither does have linkmap.txt

When I run

`x86_64-build_apple-darwin16.3.0-gcc 
  /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/cross-rpc_main.o 
  /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/cross-rpc_hout.o 
  /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/cross-rpc_cout.o 
  /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/cross-rpc_parse.o 
  /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/cross-rpc_scan.o 
  /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/cross-rpc_util.o 
  /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/cross-rpc_svcout.o 
  /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/cross-rpc_clntout.o 
  /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/cross-rpc_tblout.o 
  /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/cross-rpc_sample.o 
  -L/Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/buildtools/lib -framework CoreFoundation -lintl 
  -o /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/cross-rpcgen 
  -Wl,-map,linker.txt`

I only see this

Undefined symbols for architecture x86_64:
  "__nl_msg_cat_cntr", referenced from:
      _libintl_setlocale in libintl.a(setlocale.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I am still looking around. Any suggestions?

**Comment by stilor** [comment]
It should've been created in the current directory when you execute this command (i.e. in the `sunrpc` subdir). But this may be yet another difference between GNU toolchain and clang - GNU linker creates this file even if the link is not successful - the map file contains the "log" of all the linker actions before the linking was aborted.

You can try compiling a sample app using the libintl headers/library installed in `.build/${CT_TARGET}/buildtools` and see if it succeeds. I probably won't be able to look at this more until after the New Year - I'll try to reproduce the issue on a Linux machine with clang toolchain then.

**Comment by oxoocoffee** [comment]
When you state current directory. From your previous post do you mean 

Initial cd /Volumes/Yocto/crosstool-ng/.build/src/glibc-2.23/sunrpc or final output where 
cross-rpcgen is generated?

/Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-libc-startfiles/multilib/sunrpc/

**Comment by stilor** [comment]
The former, i.e. "current in bash sense".

**Comment by oxoocoffee** [comment]
Happy New Year. May this patch be finalized and make 2017 great :)

Ok, back to reality... I can arrange for remote access to MacOS/ssh. would this work?
Or should we continue the old way or IRC?

**Comment by stilor** [comment]
Yes, ssh would make things much more interactive. Let's connect on IRC to hash out the details.

**Comment by stilor** [comment]
@bhundven Let's merge this - this already is a few commits over your suggested threshold of 5 per PR :) This makes MacOS build pass-1 gcc. Further changes will be in a separate PR.

**Comment by stilor** [comment]
With these changes (and selecting strace 4.5.18 instead of 4.10) MacOS build succeeds.
strace has a regression - it apparently confuses build/host compilers in recent versions. Newest, 4.15, has the same issue. Will look at it separately; @bhundven - please review so we can stop piling more and more commits in this PR :)

PS. Thanks to @oxoocoffee for setting up remote access to a MacOS build machine - this has made debugging much easier.

**Comment by stilor** [comment]
And, the fix for strace. This is more of a hack to keep already released versions happy; I shall discuss the solution for future strace releases with strace maintainers.

@bhundven, the longer you delay the review, the more commits end up on this branch :)

**Comment by stilor** [comment]
Rebased after "ARM toolchain update".

**Comment by stilor** [comment]
BTW, for some reason GitHub shows the commits in different order than they are ordered on the branch. For example, the commit shown as last ("Darwin needs -liconv") is actually right after "Avoid trampling user's LDFLAGS_FOR_HOST".

**Comment by tsjk** [comment]
I don't quite understand whether this was solved in the end or not. I'm trying to build an ALARMPI1 (http://archlinuxarm.org/builder/xtools/xtools-dotconfig-v6) toolchain on OS X, and hit the problem where I get an -framework flag before the path to libiberty.a. I manage to build the chain with 240-g34ca68e3 (after adding --disable-werror to EXTRA_CONFIG_ARRAYS of GCC), but the latest trunk doesn't do it. Could somebody explain, please?

**Comment by tsjk** [comment]
Builds with 330-g6785440c as well, but I do get:
[ERROR]    clang: error: unsupported option '-print-multi-os-directory'
[ERROR]    clang: error: no input files

**Comment by stilor** [comment]
Well, it worked on @oxoocoffee 's machine. I don't have a macos to test, but @oxoocoffee said he'll provide a write-up on setting up the machine.

Some older versions may have built, but they won't work once the build tree is deleted. The problem with `-framework` is solved in a patch that we have for all supported GCC versions in crosstool-ng, but you're using a custom GCC. FWIW, I don't see an official 6.3.1 release, so if you're using something hand-rolled, you'll need to evaluate and apply the patches yourself.

**Comment by tsjk** [comment]
Aha. Yes. Arch is a bit odd with their versioning. I'll try to make the applying of the patches happen during my build process.

**Pull request merged**
