### PR TITLE
scripts/gcc: Add extra include dir with -idirafter

### PR DESCRIPTION
**Pull request by jnohlgard**
Fixes Canadian cross builds failing with missing include file `stdio.h` when building libstdc++ for a companion libc with system libc set to `LIBC_NONE`.

### CODE REVIEW

**Comment by jnohlgard** [comment]
Using a config based on samples/arm-picolibc-eabi but configured for Canadian cross compile fails without this patch.

<details><summary><tt>x86_64-pc-linux-gnu,arm-picolibc-eabi.config</tt> configuration to verify with</summary>

```sh
CT_CONFIG_VERSION="4"
CT_ARCH_ARM=y
CT_MULTILIB=y
CT_TARGET_CFLAGS="-ftls-model=local-exec"
CT_TARGET_VENDOR="picolibc"
CT_CANADIAN=y
CT_HOST="x86_64-pc-linux-gnu"
CT_LIBC_NONE=y
CT_CC_GCC_MULTILIB_LIST="rmprofile"
CT_CC_GCC_CONFIG_TLS=y
CT_CC_GCC_LTO_ZSTD=m
CT_CC_LANG_CXX=y
CT_COMP_LIBS_PICOLIBC=y
```

</details>

The errors I get when using the above config on current master without this patch look like this:

`/work/picolibc-toolchain/build-pr-test/.build/HOST-x86_64-pc-linux-gnu/arm-picolibc-eabi/src/gcc/libgcc/../gcc/tsystem.h:87:10: fatal error: stdio.h: No such file or directory`

Not sure exactly what is different between a canadian and regular cross build in the gcc configuration, but the logs show that the configure script on a regular cross finds the target compiler as xgcc with some extra -isystem flags while the Canadian cross logs show that the configure script only uses the target compiler without any automatic extra include flags, so instead we add them manually using CFLAGS_FOR_TARGET.

**Comment by jnohlgard** [comment]
Added the Canadian cross test config to the samples directory.

**Comment by jnohlgard** [comment]
Fixes #1850

**Review by cpackham — CHANGES_REQUESTED** [review]
Could you put a bit in the commit message about why this change makes sense? I don't know if `-z` is any more or less portable than `= ""` (I did check that it is in posix) so I could take or leave this change. It does appear that `-z` is used more throughout crosstool-ng so that may be justification enough.

**Comment by jnohlgard** [comment]
Updated the commit message in the first commit. The change for the if statements felt too small to warrant opening a separate PR so they got to piggyback on this one.

**Review by cpackham — APPROVED** [review]

**Pull request merged**
