### PR TITLE
Fixes for #1122

### PR DESCRIPTION
**Pull request by jhol**

### CODE REVIEW

**Comment by cpackham** [comment]
@bhundven are you able to take a glance at this series. This looks good to me but since you added the original code you might remember why the LDFLAGS additions were needed

**Comment by jhol** [comment]
@cpackham since there has been no response from @bhundven , are any automated tests that we can run to ensure that all the GCC builds are still working? I see the `testing/` subdirectory conatinaing docker conatiners for various platforms, but it's not clear to me what suite of tests is available and how to run them.

**Comment by cpackham** [comment]
The CI builds have all run and passed so thats a great start. I think
that's enough to merge this PR (post the 1.25 release).

After that we'll shake out any latent issues as we go.

**Comment by jhol** [comment]
:+1:

**Pull request merged**
