### PR TITLE
A bunch of upgrades

### PR DESCRIPTION
**Pull request by stilor**

### CODE REVIEW

**Comment by stilor** [comment]
@jcmvbkbc gas from binutils-2.30 fails while compiling libgcc for xtensa:
````
[ALL  ]    /home/avn/work/ctng/issues-ctng/.build/xtensa-fsf-linux-uclibc/build/build-cc-gcc-core-pass-2/./gcc/xgcc -B/home/avn/work/ctng/issues-ctng/.build/xtensa-fsf-linux-uclibc/build/build-cc-gcc-core-pass-2/./gcc/ -B/home/avn/work/ctng/issues-ctng/.build/xtensa-fsf-linux-uclibc/buildtools/xtensa-fsf-linux-uclibc/bin/ -B/home/avn/work/ctng/issues-ctng/.build/xtensa-fsf-linux-uclibc/buildtools/xtensa-fsf-linux-uclibc/lib/ -isystem /home/avn/work/ctng/issues-ctng/.build/xtensa-fsf-linux-uclibc/buildtools/xtensa-fsf-linux-uclibc/include -isystem /home/avn/work/ctng/issues-ctng/.build/xtensa-fsf-linux-uclibc/buildtools/xtensa-fsf-linux-uclibc/sys-include    -mlongcalls -mtext-section-literals -g -Os -O2  -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE  -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -fPIC -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector   -fPIC -I. -I. -I../.././gcc -I/home/avn/work/ctng/issues-ctng/.build/xtensa-fsf-linux-uclibc/src/gcc/libgcc -I/home/avn/work/ctng/issues-ctng/.build/xtensa-fsf-linux-uclibc/src/gcc/libgcc/. -I/home/avn/work/ctng/issues-ctng/.build/xtensa-fsf-linux-uclibc/src/gcc/libgcc/../gcc -I/home/avn/work/ctng/issues-ctng/.build/xtensa-fsf-linux-uclibc/src/gcc/libgcc/../include  -DHAVE_CC_TLS  -o _addsubsf3_s.o -MT _addsubsf3_s.o -MD -MP -MF _addsubsf3_s.dep -DSHARED -DL_addsubsf3 -xassembler-with-cpp -c /home/avn/work/ctng/issues-ctng/.build/xtensa-fsf-linux-uclibc/src/gcc/libgcc/config/xtensa/lib1funcs.S
[ALL  ]    /home/avn/work/ctng/issues-ctng/.build/xtensa-fsf-linux-uclibc/src/gcc/libgcc/config/xtensa/ieee754-sf.S: Assembler messages:
[ALL  ]    /home/avn/work/ctng/issues-ctng/.build/xtensa-fsf-linux-uclibc/src/gcc/libgcc/config/xtensa/ieee754-sf.S:82: Error: literal pool location required for text-section-literals; specify with .literal_position
[ALL  ]    /tmp/ccRZSRE5.s: Internal error in xtensa_move_literals at /home/avn/work/ctng/issues-ctng/.build/xtensa-fsf-linux-uclibc/src/binutils/gas/config/tc-xtensa.c:11319.
[ALL  ]    Please report this bug.
[ALL  ]    Makefile:481: recipe for target '_addsubsf3_s.o' failed
````
Any patches for this up your sleeve? If not, I am going to restrict xtensa to 2.29 and below for now.

**Comment by stilor** [comment]
Correction: 2.29.1 fails as well, apparently this is because of gcc 7.3...

**Comment by jcmvbkbc** [comment]
https://github.com/jcmvbkbc/gcc-xtensa/commit/4d008fbf4056320ac46981414c890f9b0d2dafd6 should fix that

**Comment by stilor** [comment]
It does, but the same fix is needed in ieee754-df.S as well.

**Comment by egtvedt** [comment]
GDB released 8.1 today, would be nice to get included.

**Comment by stilor** [comment]
In the next batch; I am running ct-ng build-all to test this and it has already gone through ~60% of the samples. I don't want to restart its run :)

Besides, there's also glibc release scheduled to go out today, and in #905 a new gcc-linaro release was mentioned (although I don't see it on releases.linaro.org). There will be a separate batch on the heels of this one :)

**Comment by stilor** [comment]
build-all passes.

**Pull request merged**
