### PR TITLE
Fixed travis-ci environment setting

### PR DESCRIPTION
**Pull request by jasmin-j**
Set language to 'bash' to get rid of interfering environment variable CC=gcc.

Signed-off-by: Jasmin Jessich <jasmin@anw.at>

### CODE REVIEW

**Comment by bhundven** [comment]
Well, we'll see if the PR fixes it in the PR build :)

**Comment by bhundven** [comment]
Seems to still fail.

**Comment by jasmin-j** [comment]
It DID fix the compile problem of the native GDB on travis-ci! Please see the log.

But it didn't fix the compile problem of ltrace 0.7.3, because this is no problem of travis-ci, but of the
new patches to ltrace 0.7.3. Please read my comment in #180 beginning with "@bhundven" and
talking about ltrace-0.5.3 and ltrace-0.7.3.

Please merge it to master, it is definitely required to build a compiler for Linux as target on travis-ci.

**Comment by bhundven** [comment]
Something is up with ltrace. I've tried a bunch of different things with it, and am thinking about dropping it. It could be supplied by buildroot or some other higher level system.

**Comment by jasmin-j** [comment]
As I checked already, you can use  ltrace-0.5.3 or remove the patches from the commit I mentioned.
I didn't try to compile 0.7.3 without the patches, but it worked for long time.
Or someone can fix it ... .

**Comment by jasmin-j** [comment]
Please close this now.

**Pull request merged**
