### PR TITLE
Support mpc V 1.0.3

### PR DESCRIPTION
**Pull request by jasmin-j**
Support mpc 1.0.3 in configuration.

Signed-off-by: Jasmin Jessich <jasmin@anw.at>

### CODE REVIEW

**Comment by jasmin-j** [comment]
Which target would you like to build?

**Comment by bhundven** [comment]
It shouldn't matter which target.

**Comment by jasmin-j** [comment]
I built a powerpc-unknown-linux-gnu cross compiler. The build of core gcc 4.5.3 worked, but libc expected a newer gcc version.

> Or do we need a constraint so that it only builds with newer versions of gcc?
No, I guess not.

Last lines of build.log:
 [CFG  ]    checking for gawk... gawk
 [CFG  ]    checking version of gawk... 4.0.1, ok
 [CFG  ]    checking if powerpc-unknown-linux-gnu-gcc     is sufficient to build libc... no
 [CFG  ]    checking for powerpc-unknown-linux-gnu-nm... powerpc-unknown-linux-gnu-nm
 [ERROR]    configure: error: 
 [CFG  ]    *** These critical programs are missing or too old: compiler
 [CFG  ]    *** Check the INSTALL file for required versions.

Build Log (stdout):
[INFO ]  Retrieving needed toolchain components' tarballs
[EXTRA]    Retrieving 'linux-4.1.4'
[EXTRA]    Saving 'linux-4.1.4.tar.xz' to local storage
[EXTRA]    Retrieving 'ppl-0.11.2'
[EXTRA]    Saving 'ppl-0.11.2.tar.lzma' to local storage
[EXTRA]    Retrieving 'cloog-ppl-0.15.11'
[EXTRA]    Saving 'cloog-ppl-0.15.11.tar.gz' to local storage
[EXTRA]    Retrieving 'libelf-0.8.13'
[EXTRA]    Saving 'libelf-0.8.13.tar.gz' to local storage
[EXTRA]    Retrieving 'binutils-2.25'
[EXTRA]    Saving 'binutils-2.25.tar.bz2' to local storage
[EXTRA]    Retrieving 'gcc-4.5.3'
[EXTRA]    Saving 'gcc-4.5.3.tar.bz2' to local storage
[EXTRA]    Retrieving 'glibc-2.21'
[EXTRA]    Saving 'glibc-2.21.tar.xz' to local storage
[EXTRA]    Retrieving 'duma_2_5_15'
[EXTRA]    Saving 'duma_2_5_15.tar.gz' to local storage
[EXTRA]    Retrieving 'ncurses-5.9'
[EXTRA]    Saving 'ncurses-5.9.tar.gz' to local storage
[EXTRA]    Retrieving 'expat-2.1.0'
[EXTRA]    Saving 'expat-2.1.0.tar.gz' to local storage
[EXTRA]    Retrieving 'strace-4.10'
[EXTRA]    Saving 'strace-4.10.tar.xz' to local storage
[INFO ]  Retrieving needed toolchain components' tarballs: done in 391.26s (at 06:33)
[INFO ]  =================================================================
[INFO ]  Extracting and patching toolchain components
[EXTRA]    Extracting 'linux-4.1.4'
[EXTRA]    Patching 'linux-4.1.4'
[EXTRA]    Extracting 'gmp-6.0.0a'
[EXTRA]    Patching 'gmp-6.0.0a'
[EXTRA]    Extracting 'mpfr-3.1.3'
[EXTRA]    Patching 'mpfr-3.1.3'
[EXTRA]    Extracting 'ppl-0.11.2'
[EXTRA]    Patching 'ppl-0.11.2'
[EXTRA]    Extracting 'cloog-ppl-0.15.11'
[EXTRA]    Patching 'cloog-ppl-0.15.11'
[EXTRA]    Extracting 'mpc-1.0.3'
[EXTRA]    Patching 'mpc-1.0.3'
[EXTRA]    Extracting 'libelf-0.8.13'
[EXTRA]    Patching 'libelf-0.8.13'
[EXTRA]    Extracting 'binutils-2.25'
[EXTRA]    Patching 'binutils-2.25'
[EXTRA]    Extracting 'gcc-4.5.3'
[EXTRA]    Patching 'gcc-4.5.3'
[EXTRA]    Extracting 'glibc-2.21'
[EXTRA]    Patching 'glibc-2.21'
[EXTRA]    Extracting 'duma_2_5_15'
[EXTRA]    Patching 'duma-2_5_15'
[EXTRA]    Extracting 'gdb-7.9.1'
[EXTRA]    Patching 'gdb-7.9.1'
[EXTRA]    Extracting 'ncurses-5.9'
[EXTRA]    Patching 'ncurses-5.9'
[EXTRA]    Extracting 'expat-2.1.0'
[EXTRA]    Patching 'expat-2.1.0'
[EXTRA]    Extracting 'strace-4.10'
[EXTRA]    Patching 'strace-4.10'
[INFO ]  Extracting and patching toolchain components: done in 44.69s (at 07:17)
[INFO ]  =================================================================
[INFO ]  Installing GMP for host
[EXTRA]    Configuring GMP
[EXTRA]    Building GMP
[EXTRA]    Installing GMP
[INFO ]  Installing GMP for host: done in 33.62s (at 07:51)
[INFO ]  =================================================================
[INFO ]  Installing MPFR for host
[EXTRA]    Configuring MPFR
[EXTRA]    Building MPFR
[EXTRA]    Installing MPFR
[INFO ]  Installing MPFR for host: done in 24.87s (at 08:16)
[INFO ]  =================================================================
[INFO ]  Installing PPL for host
[EXTRA]    Configuring PPL
[EXTRA]    Building PPL
[EXTRA]    Installing PPL
[INFO ]  Installing PPL for host: done in 153.88s (at 10:50)
[INFO ]  =================================================================
[INFO ]  Installing CLooG for host
[EXTRA]    Configuring CLooG
[EXTRA]    Building CLooG
[EXTRA]    Installing CLooG
[INFO ]  Installing CLooG for host: done in 4.76s (at 10:55)
[INFO ]  =================================================================
[INFO ]  Installing MPC for host
[EXTRA]    Configuring MPC
[EXTRA]    Building MPC
[EXTRA]    Installing MPC
[INFO ]  Installing MPC for host: done in 10.56s (at 11:05)
[INFO ]  =================================================================
[INFO ]  Installing libelf for host
[EXTRA]    Configuring libelf
[EXTRA]    Building libelf
[EXTRA]    Installing libelf
[INFO ]  Installing libelf for host: done in 4.73s (at 11:10)
[INFO ]  =================================================================
[INFO ]  Installing binutils for host
[EXTRA]    Configuring binutils
[EXTRA]    Building binutils
[EXTRA]    Installing binutils
[INFO ]  Installing binutils for host: done in 62.62s (at 12:13)
[INFO ]  =================================================================
[INFO ]  Installing pass-1 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[EXTRA]    Installing gcc
[INFO ]  Installing pass-1 core C gcc compiler: done in 219.50s (at 15:52)
[INFO ]  =================================================================
[INFO ]  Installing kernel headers
[EXTRA]    Installing kernel headers
[EXTRA]    Checking installed headers
[INFO ]  Installing kernel headers: done in 6.17s (at 15:58)
[INFO ]  =================================================================
[INFO ]  Installing C library headers & start files
[EXTRA]    Configuring C library
[ERROR]    configure: error: 
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing C library headers & start files'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@257]
[ERROR]  >>        called from: do_libc_backend_once[scripts/build/libc/glibc.sh@346]
[ERROR]  >>        called from: do_libc_backend[scripts/build/libc/glibc.sh@151]
[ERROR]  >>        called from: do_libc_start_files[scripts/build/libc/glibc.sh@68]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@638]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/home/jasmin/jasmin_hdd/SW/crosstool-ng/crosstool-ng/docs/B - Known issues.txt'
[ERROR]   
[ERROR]  (elapsed: 15:59.83)

**Comment by bhundven** [comment]
From the glibc-2.21 release notes:

```
* The minimum GCC version that can be used to build this version of the GNU
  C Library is GCC 4.6.  Older GCC versions, and non-GNU compilers, can
  still be used to compile programs using the GNU C Library.
```

**Comment by bhundven** [comment]
You could try glibc-2.20.

**Comment by jasmin-j** [comment]
I used now glibc-2.20, but still got errors.
The errors were independent of the mpc/mpfr versions!
The same error with mpc 1.0.2/mpfr 3.1.2 and mpc 1.0.3/mpfr 3.1.3.
From my point of view you can apply my patch and someone can have a look why gcc 4.5.3 does not work (but it does compile!) for powerpc-unknown-linux-gnu.

Maybe you can suggest another target to test?

Build Log (stdout), same for mpc 1.0.2/mpfr 3.1.2 and mpc 1.0.3/mpfr 3.1.3:
[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20150901.235627
[INFO ]  Building environment variables
[EXTRA]  Preparing working directories
[EXTRA]  Installing user-supplied crosstool-NG configuration
[EXTRA]  =================================================================
[EXTRA]  Dumping internal crosstool-NG configuration
[EXTRA]    Building a toolchain for:
[EXTRA]      build  = x86_64-unknown-linux-gnu
[EXTRA]      host   = x86_64-unknown-linux-gnu
[EXTRA]      target = powerpc-unknown-linux-gnu
[EXTRA]  Dumping internal crosstool-NG configuration: done in 0.06s (at 00:01)
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[EXTRA]    Retrieving 'mpfr-3.1.2'
[EXTRA]    Saving 'mpfr-3.1.2.tar.xz' to local storage
[EXTRA]    Retrieving 'mpc-1.0.2'
[EXTRA]    Saving 'mpc-1.0.2.tar.gz' to local storage
[INFO ]  Retrieving needed toolchain components' tarballs: done in 4.56s (at 00:05)
[INFO ]  =================================================================
[INFO ]  Extracting and patching toolchain components
[EXTRA]    Extracting 'linux-4.1.4'
[EXTRA]    Patching 'linux-4.1.4'
[EXTRA]    Extracting 'gmp-6.0.0a'
[EXTRA]    Patching 'gmp-6.0.0a'
[EXTRA]    Extracting 'mpfr-3.1.2'
[EXTRA]    Patching 'mpfr-3.1.2'
[EXTRA]    Extracting 'ppl-0.11.2'
[EXTRA]    Patching 'ppl-0.11.2'
[EXTRA]    Extracting 'cloog-ppl-0.15.11'
[EXTRA]    Patching 'cloog-ppl-0.15.11'
[EXTRA]    Extracting 'mpc-1.0.2'
[EXTRA]    Patching 'mpc-1.0.2'
[EXTRA]    Extracting 'libelf-0.8.13'
[EXTRA]    Patching 'libelf-0.8.13'
[EXTRA]    Extracting 'binutils-2.25'
[EXTRA]    Patching 'binutils-2.25'
[EXTRA]    Extracting 'gcc-4.5.3'
[EXTRA]    Patching 'gcc-4.5.3'
[EXTRA]    Extracting 'glibc-2.20'
[EXTRA]    Patching 'glibc-2.20'
[EXTRA]    Extracting 'duma_2_5_15'
[EXTRA]    Patching 'duma-2_5_15'
[EXTRA]    Extracting 'gdb-7.9.1'
[EXTRA]    Patching 'gdb-7.9.1'
[EXTRA]    Extracting 'ncurses-5.9'
[EXTRA]    Patching 'ncurses-5.9'
[EXTRA]    Extracting 'expat-2.1.0'
[EXTRA]    Patching 'expat-2.1.0'
[EXTRA]    Extracting 'strace-4.10'
[EXTRA]    Patching 'strace-4.10'
[INFO ]  Extracting and patching toolchain components: done in 44.08s (at 00:49)
[INFO ]  =================================================================
[INFO ]  Installing GMP for host
[EXTRA]    Configuring GMP
[EXTRA]    Building GMP
[EXTRA]    Installing GMP
[INFO ]  Installing GMP for host: done in 35.01s (at 01:25)
[INFO ]  =================================================================
[INFO ]  Installing MPFR for host
[EXTRA]    Configuring MPFR
[EXTRA]    Building MPFR
[EXTRA]    Installing MPFR
[INFO ]  Installing MPFR for host: done in 15.22s (at 01:40)
[INFO ]  =================================================================
[INFO ]  Installing PPL for host
[EXTRA]    Configuring PPL
[EXTRA]    Building PPL
[EXTRA]    Installing PPL
[INFO ]  Installing PPL for host: done in 154.83s (at 04:15)
[INFO ]  =================================================================
[INFO ]  Installing CLooG for host
[EXTRA]    Configuring CLooG
[EXTRA]    Building CLooG
[EXTRA]    Installing CLooG
[INFO ]  Installing CLooG for host: done in 4.87s (at 04:19)
[INFO ]  =================================================================
[INFO ]  Installing MPC for host
[EXTRA]    Configuring MPC
[EXTRA]    Building MPC
[EXTRA]    Installing MPC
[INFO ]  Installing MPC for host: done in 5.67s (at 04:25)
[INFO ]  =================================================================
[INFO ]  Installing libelf for host
[EXTRA]    Configuring libelf
[EXTRA]    Building libelf
[EXTRA]    Installing libelf
[INFO ]  Installing libelf for host: done in 4.73s (at 04:30)
[INFO ]  =================================================================
[INFO ]  Installing binutils for host
[EXTRA]    Configuring binutils
[EXTRA]    Building binutils
[EXTRA]    Installing binutils
[INFO ]  Installing binutils for host: done in 64.00s (at 05:34)
[INFO ]  =================================================================
[INFO ]  Installing pass-1 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[EXTRA]    Installing gcc
[INFO ]  Installing pass-1 core C gcc compiler: done in 220.91s (at 09:15)
[INFO ]  =================================================================
[INFO ]  Installing kernel headers
[EXTRA]    Installing kernel headers
[EXTRA]    Checking installed headers
[INFO ]  Installing kernel headers: done in 5.77s (at 09:21)
[INFO ]  =================================================================
[INFO ]  Installing C library headers & start files
[EXTRA]    Configuring C library
[EXTRA]    Installing C library headers
[EXTRA]    Installing C library start files
[INFO ]  Installing C library headers & start files: done in 9.37s (at 09:30)
[INFO ]  =================================================================
[INFO ]  Installing pass-2 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[EXTRA]    Installing gcc
[INFO ]  Installing pass-2 core C gcc compiler: done in 239.17s (at 13:29)
[INFO ]  =================================================================
[INFO ]  Installing C library
[EXTRA]    Configuring C library
[EXTRA]    Building C library
[EXTRA]    Installing C library
[INFO ]  Installing C library: done in 254.58s (at 17:44)
[INFO ]  =================================================================
[INFO ]  Installing final gcc compiler
[EXTRA]    Configuring final gcc compiler
[EXTRA]    Building final gcc compiler
[ERROR]    checking for string.h... checking for library containing strerror... configure: error: Link tests are not allowed after GCC_NO_EXECUTABLES.
[ERROR]    checking for memory.h... make[2]: *** [configure-target-libiberty] Error 1
[ERROR]    checking dynamic linker characteristics... configure: error: Link tests are not allowed after GCC_NO_EXECUTABLES.
[ERROR]    make[2]: *** [configure-target-libstdc++-v3] Error 1
[ERROR]    make[1]: *** [all] Error 2

**Comment by bhundven** [comment]
We'll revisit any constraints in future bug reports :)

**Comment by bhundven** [comment]
Thanks!

**Pull request merged**
