### PR TITLE
Disable libmpx in x86-musl.

### PR DESCRIPTION
**Pull request by stilor**
GCC 6.1.0 (final compiler) fails to compile against musl.

Signed-off-by: Alexey Neyman <stilor@att.net>

### CODE REVIEW

**Comment by bhundven** [comment]
Does this patch help?
https://github.com/gentoo/musl/blob/master/sys-devel/gcc/files/gcc-6.1.0-musl-cpu.patch

**Comment by bhundven** [comment]
Maybe it would be good to dump a build log of it failing?

**Comment by stilor** [comment]
Build failure:
````
[ALL  ]    In file included from /home/avn/work/ctng/crosstool-ng/.build/src/gcc-6.1.0/libmpx/mpxrt/mpxrt.c:54:0:
[ALL  ]    /home/avn/work/ctng/crosstool-ng/.build/src/gcc-6.1.0/libmpx/mpxrt/mpxrt.c: In function 'read_mpx_status_sig':
[ERROR]    /home/avn/work/ctng/crosstool-ng/.build/src/gcc-6.1.0/libmpx/mpxrt/mpxrt.h:52:42: error: invalid application of 'sizeof' to incomplete type 'struct _libc_fpstate'
[ALL  ]     #define XSAVE_OFFSET_IN_FPMEM    sizeof (struct _libc_fpstate)
[ALL  ]                                              ^
[ALL  ]    /home/avn/work/ctng/crosstool-ng/.build/src/gcc-6.1.0/libmpx/mpxrt/mpxrt.c:132:58: note: in expansion of macro 'XSAVE_OFFSET_IN_FPMEM'
[ALL  ]       uint8_t *regs = (uint8_t *)uctxt->uc_mcontext.fpregs + XSAVE_OFFSET_IN_FPMEM;
[ALL  ]                                                              ^~~~~~~~~~~~~~~~~~~~~
[ALL  ]    no
[ALL  ]    checking for _isnanf declaration... Makefile:387: recipe for target 'libmpx_la-mpxrt.lo' failed
[ERROR]    make[9]: *** [libmpx_la-mpxrt.lo] Error 1
[ALL  ]    make[9]: *** Waiting for unfinished jobs....
````

**Comment by stilor** [comment]
... and no, the patch above does not fix the issue.

**Comment by KirillSmirnov** [comment]
Does CT_CC_GCC_EXTRA_CONFIG_ARRAY="--disable-libmpx" help?

**Comment by KirillSmirnov** [comment]
This config works for me:

CT_EXPERIMENTAL=y
CT_LOCAL_TARBALLS_DIR="${HOME}/src"
CT_SAVE_TARBALLS=y
CT_LOG_EXTRA=y
CT_ARCH_64=y
CT_ARCH_x86=y
CT_MULTILIB=y
CT_TARGET_VENDOR="multilib"
CT_KERNEL_linux=y
# CT_KERNEL_LINUX_INSTALL_CHECK is not set
CT_BINUTILS_LINKER_LD_GOLD=y
CT_BINUTILS_GOLD_THREADS=y
CT_BINUTILS_LD_WRAPPER=y
CT_BINUTILS_PLUGINS=y
CT_LIBC_musl=y
CT_CC_GCC_EXTRA_CONFIG_ARRAY="--disable-libmpx"
CT_CC_LANG_CXX=y

**Comment by stilor** [comment]
Works for me, too.

**Comment by stilor** [comment]
If you want more permanent solution, I think 100-gcc.sh and appropriate config option (`CC_GCC_LIBMPX`, dependent on `!LIBC_musl`) would be more appropriate. I don't think it right to create a spaghetti by having musl.sh change the options for gcc.sh.

Do you agree?

**Comment by bhundven** [comment]
Yes, I like that better. Then someone that uses a different sample but still uses musl won't be opening a duplicate issue.

**Comment by stilor** [comment]
Ping?

**Comment by bhundven** [comment]
The branch is out of date, and that stops me from merging the change. Please update the branch and I'll get this merged.

**Comment by stilor** [comment]
Branch updated & rebuilt.

**Comment by bhundven** [comment]
Thanks!

**Pull request merged**
