### PR TITLE
travis-ci: Enable new automated build option

### PR DESCRIPTION
**Pull request by bhundven**
Signed-off-by: Bryan Hundven <bryanhundven@gmail.com>

### CODE REVIEW

**Comment by bhundven** [comment]
Hrm. gcc does sometimes take > 10 minutes to compile. Is there a way to extend the timeout?

**Comment by bhundven** [comment]
I also note: "All checks have failed", where 4 tests were ran, and 2 failed. I'd like a fix for that as well.

**Comment by jasmin-j** [comment]
> Is there a way to extend the timeout?

Theoretically you could use "travis_wait" (see: http://docs.travis-ci.com/user/build-timeouts/#Build-times-out-because-no-output-was-received), but this will work for 20 minutes only.
I guess the approach from JML #193 is a better solution.

**Comment by jmlemetayer** [comment]
@jasmin-j The #193 is actually inspired by [`travis_wait`](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/templates/header.sh#L108).

@bhundven I think the whole matrix build (the 4 builds) count for one test only.

**Comment by jasmin-j** [comment]
> I think the whole matrix build (the 4 builds) count for one test only. See this blog post.

I don't believe this. When you look to [this] (https://travis-ci.org/crosstool-ng/crosstool-ng/builds/83047634) build result, the sum of all the builds does exceed 50 minutes (ran for 2 hrs 35 min 16 sec).
Or do they count CPU time instead of real elapsed minutes?

**Comment by jmlemetayer** [comment]
I think, the total time restriction applies to a single virtual machine. So in our case for each sample. Moreover, regarding [my first build which I cancelled manually after 1h15](https://travis-ci.org/jmlemetayer/crosstool-ng/builds/80435130), the total time has probably been extended.

**Comment by bhundven** [comment]
A better solution was found in #202

**Pull request closed without merging**
