### PR TITLE
Fix for issue #145:

### PR DESCRIPTION
**Pull request by jasmin-j**
Added gcc version selection if CC_GCC_CUSTOM is selected.
Signed-off-by: Jasmin Jessich <jasmin@anw.at>

### CODE REVIEW

**Comment by bhundven** [comment]
I'm going to hold on this change. I think there might be another way to handle this.
I'm in -08:00 (PST), and I'll look at this in the morning.

**Comment by jasmin-j** [comment]
> I think there might be another way to handle this.
I tried to reuse the already existing GCC configuration options. CT-NG supports a lot of versions and reusing this mechanism is the best I can think of.

Which other way?
What shall I try?

**Comment by yann-morin-1998** [comment]
What @bhundven and I discussed on IRC: the CC_GCC_CUSTOM option should get out of the choice.

So, you still select the version from the existing choice, and the CC_GCC_CUSTOM is now an option of its own. So, no need to duplicate the choice just to get the correct _or_later.

**Comment by jasmin-j** [comment]
OK, I will update my patches (gcc, newlib) according to this suggestion. Moreover, I will do this for Binutils and GDB too, when I have time (I need it anyway).

**Comment by bhundven** [comment]
Just out of curiosity, How are you using these changes?
I have planned work to add generic git/svn/bzr support for all packages. These seem like similar changes?

**Comment by jasmin-j** [comment]
> Just out of curiosity, How are you using these changes?

I want to build an arm-none-eabi cross compiler from this sources
   svn://gcc.gnu.org/svn/gcc/branches/ARM/embedded-4_9-branch
Later maybe newlib from here
   git://sourceware.org/git/newlib-cygwin.git

There is a script available to build this compiler, but it is not that easy for non experienced people.
And the script is only available inside of the tarball:
  https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q2-update

It is work to trim crosstool-ng to build with the exactly same  configuration parameters as the script uses, but I am sure I will manage it ;)
In the long run, I plan to use crosstool-ng to build a dedicated toolchain for a new embedded OS called distortos (arm-distortos-eabi):
   https://github.com/DISTORTEC/distortos
So it will require some patches to newlib and maybe gcc. The rest of the tools should be build out of the box. But it should be much easier to build this version with crosstool-ng, than with the script. And crosstool-ng will improve over time (see your idea with git/sv/bzr support). This is a great synergy!

> I have planned work to add generic git/svn/bzr support for all packages.

Perfekt!

> These seem like similar changes?

Not really. This would use the changes ;)
Even if you use git, svn or whatever, crosstool-ng needs to know the gcc, binutil, newlib version of the checked out sources.
I guess your checkout feature would be very useful as a pre step of the build (instead of getting the tarballs). And then you would still require a directory to checkout, which could be the custom location.
Moreover, you will need some patches for checked out versions, too. Look to the patches, they are really old and still not in the main line. Some of them might be never go there, but are required for a cross build.
At the end you will have two directories. One with the original upstream version and one with the patches applied. Your feature could be so clever to use a symbolic link, if there are no patches.

**Comment by jasmin-j** [comment]
I implemented @yann-morin-1998 suggestion on my branch "gcc_custom_version".
Closing this pull request, because it is now obsolete.

**Pull request closed without merging**
