### PR TITLE
Select KERNEL_SUPPORTS_SHARED_LIBS on Windows

### PR DESCRIPTION
**Pull request by likema**
Fix building MinGW only generating libstdc++.a

### CODE REVIEW

**Review by cpackham — CHANGES_REQUESTED** [review]
I think the right thing to do would be to add `## select KERNEL_SUPPORTS_SHARED_LIBS` to config/kernel/windows.in

**Comment by likema** [comment]
> I think the right thing to do would be to add `## select KERNEL_SUPPORTS_SHARED_LIBS` to config/kernel/windows.in

Fixed

**Review by cpackham — APPROVED** [review]

**Comment by cpackham** [comment]
For future commits please make sure to include your `Signed-off-by:`

**Comment by likema** [comment]
> Signed-off-by

Done

**Pull request merged**
