### PR TITLE
Initial GCC 14.1.0 support

### PR DESCRIPTION
**Pull request by nikkon-dev**
- gcc 14 package version
- tar.gz and tar.xz checksums
- patches from gcc13 that can still be applied to gcc14

### CODE REVIEW

**Comment by cpackham** [comment]
let's see how the builds go

**Comment by nikkon-dev** [comment]
> let's see how the builds go

I don't think that macOS build failure due to lacking the makeinfo tool is anyhow connected to the changes.

**Comment by cpackham** [comment]
Yeah not related to your stuff but maybe there has been a change to the macos runners. Are you based off the latest master?

**Comment by nikkon-dev** [comment]
> Yeah not related to your stuff but maybe there has been a change to the macos runners. Are you based off the latest master?

Yes, It was based on the latest master branch.

**Comment by nikkon-dev** [comment]
I updated the macOS CI workflows to install missing tools via Homebrew. The build passed in my branch..

**Comment by cpackham** [comment]
I've kicked off the CI run again to see what happens. For the final version please submit this as a series of 2 patches. One for the CI changes. One for the new GCC version

**Comment by nikkon-dev** [comment]
> I've kicked off the CI run again to see what happens. For the final version please submit this as a series of 2 patches. One for the CI changes. One for the new GCC version

MacOs CI PR: [2147](https://github.com/crosstool-ng/crosstool-ng/pull/2147)

I'll resubmit this one on top of the master once the 2147 is merged.

**Comment by cpackham** [comment]
Now we're on to actual failures. From arc-multilib-linux-uclibc:
```
Error:       libc/sysdeps/linux/common/futimesat.c:36:16: error: implicit declaration of function 'utimensat'; did you mean 'futimesat'? [-Wimplicit-function-declaration]
````

**Comment by nikkon-dev** [comment]
> Now we're on to actual failures. From arc-multilib-linux-uclibc:
> 
> ```
> Error:       libc/sysdeps/linux/common/futimesat.c:36:16: error: implicit declaration of function 'utimensat'; did you mean 'futimesat'? [-Wimplicit-function-declaration]
> ```

Those errors are not related to MacOS but rather actual incompatibilities with gcc14. I created https://github.com/crosstool-ng/crosstool-ng/pull/2148 to backport recent gcc14 changes from the uClibc-ng.

The gcc14 integration is proving to be a complex task. There are numerous issues with missing headers (some are not included transiently anymore) and variations in the warnings/errors that gcc14 reports. It's a daunting task to build every combination of targets/libraries versions.

How should this effort progress further?

**Comment by cpackham** [comment]
I think just keep doing what you're doing. Build one or two configurations
locally and keep updating the PR with fixes and to identify new failures.
Rinse and repeat.

**Comment by nikkon-dev** [comment]
Some helpful work was done in the compiler explorer: https://github.com/compiler-explorer/compiler-explorer/issues/6406

**Comment by nikkon-dev** [comment]
[8c371dc](https://github.com/crosstool-ng/crosstool-ng/pull/2146/commits/8c371dccc3329e9c4ffd8fa9cd2088dcb9ea5a59) commit fixed the sh-unknown-elf build

**Pull request merged**
