### PR TITLE
Updated script to support mingw versions above major 2

### PR DESCRIPTION
**Pull request by neftedal**
Tested and verified with mingw version 2.0.7, 3.3.0 and 4.0-rc3

### CODE REVIEW

**Comment by jpf91** [comment]
I can confirm this is working fine, but I've got one suggestion:
If we don't specifiy `--with-sysroot=` when configuring mingw, mingw assumes sysroot==prefix. Because of this it includes `-I/usr/i686-w64-mingw32/include` when compiling the mingw libraries. If this directory exists on the build machine it could cause all kinds of issues.

**Comment by neftedal** [comment]
Thanks for the input, Johannes. I agree that leaving out --with-prefix might indeed cause problems if the prefix dir is also located on the build machine. I've changed my pull request to include "--with-sysroot=${CT_SYSROOT_DIR}" when configuring mingw and verified that mingw v4.0-rc3 still builds fine.

**Comment by bhundven** [comment]
All looks good to me, but I'd like to see a better description in the commit and a signed-off-by, which is required by gpl. http://elinux.org/Legal_Issues#Signed-off-by_lines_and_the_DCO

Simple as doing an interactive rebase, editing the two commits in your branch, push back to your repo and this pull-request should be updated.

**Comment by neftedal** [comment]
Bryan, the commits are now updated with improved descriptions including signed-off-by

**Comment by neftedal** [comment]
Let me know if you want me to change something else or if it has a go for merging as is.

**Comment by bhundven** [comment]
Nope, looks good to me. Thanks!

**Pull request merged**
