### PR TITLE
Adds Raspberry Pi 3 sample config

### PR DESCRIPTION
**Pull request by kongen**
Adds a new sample configuration for Raspberry Pi 3, based on BCM2837 (ARM Cortex A53)

### CODE REVIEW

**Comment by bhundven** [comment]
Nak, need a "Signed-off-by: name <email>"

**Comment by kongen** [comment]
How do I get that - or, you just looking for me to add this to the commit message ?

**Comment by bhundven** [comment]
Yea, just ```git commit --amend```, add another line in the commit message with the signed-off-by, and ```git push --force [remote] [branch]``` to update this PR. :)

**Comment by kongen** [comment]
Updated ;=)

**Comment by bhundven** [comment]
Awesome, thanks!

**Pull request merged**
