### PR TITLE
Add the support to choose, download and build latest Linaro toolchain components

### PR DESCRIPTION
**Pull request by Christopher83**

### CODE REVIEW

**Comment by bhundven** [comment]
@Christopher83 I'm glad you have finally posted this pull request!

I'm hesitant changes to eglibc, as I'm planning to remove support for eglibc since it is no longer actively developed. But, that is a topic of discussion that may take a while to actually happen.

It may take me a bit of time until I can fully review these, but I'll try to quickly run through them and point out anything that stands out.

**Comment by bhundven** [comment]
my only gripe is use of ```sed``` instead of ```${sed}```. There are other spots in the source where ```sed``` is used, and hopefully I can get around to refactoring them to be ```${sed}``` in the near future.

**Comment by Christopher83** [comment]
Thanks @bhundven,
I replaced the sed calls as you suggested and rebased the pull, I hope it's fine now...
Regards

**Comment by bhundven** [comment]
@Christopher83 Looks good to me. I'm going to wait a few days to see if anyone else has comments, then I'll merge it! Thanks!

**Comment by Christopher83** [comment]
Ok, thank you too!

**Comment by Christopher83** [comment]
Hi @bhundven,
I rebased the commits, merged the conflicts and updated the commit related to Linaro GCC (for 4.9-2015.01) and the commit related to kernel versions.

**Comment by bhundven** [comment]
@Christopher83 Thanks!

**Pull request merged**
