### PR TITLE
samples: Add sparc-leon-linux-uclibc sample

### PR DESCRIPTION
**Pull request by KirillSmirnov**
Add a toolchain for leon2 cpu without fp unit.

Signed-off-by: Kirill K. Smirnov <kirill.k.smirnov@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/crosstool-ng/crosstool-ng/409)

### CODE REVIEW

**Comment by KirillSmirnov** [comment]
Strange. How come arm-unknown-linux-gnueabi toolchain failed while my commit adds configs for sparc only?

**Comment by bhundven** [comment]
Sorry for the delay...

https://travis-ci.org/crosstool-ng/crosstool-ng/jobs/147309426

It looks like it had a problem downloading strace. I've restarted the build for that target.

**Comment by bhundven** [comment]
Watching the build:

```
[EXTRA]    Extracting 'ltrace-0.7.3'
[EXTRA]    Patching 'ltrace-0.7.3'
[EXTRA]    Extracting 'strace-4.10'
[EXTRA]    Patching 'strace-4.10'
[INFO ]  Extracting and patching toolchain components: done in 49.34s (at 00:51)
```

The build rolls on. :)

**Comment by bhundven** [comment]
Thanks!

**Pull request merged**
