### PR TITLE
Updates to make `ct-ng build-all` pass

### PR DESCRIPTION
**Pull request by stilor**
I am still re-running build-all after the latest rebase and fixing the last two samples, but barring any surprises, it should be now passing at least on my Ubuntu 21.10.

Finish incomplete removal of obsolete milestones. Finish the conversion of GCC build into two-pass (the "libc_headers" step mentioned in that commit is actually needed to unbreak xtensa samples).

Also, update/fix docker images that can be used to run the build in various Linux flavors. Randomly tested with a single sample in each, I hope to resurrect my dedicated build machine for running `ct-ng build-all` repeatedly.

### CODE REVIEW

**Review by cpackham — APPROVED** [review]

**Comment by cpackham** [comment]
@stilor looks good to me. Let me know if you want me to do merge the PR.

**Comment by stilor** [comment]
Just to confirm, `ct-ng build-all` passed in the commit I posted. Hope new binutils don't break anything :)

**Comment by cpackham** [comment]
I think it should be fine. The differences between 2.37 and 2.38 aren't huge and both series had clean CI runs.

Are there any configurations you think are worth adding to the CI builds? We don't have any coverage for bionic so that's an obvious one. I'd also like to include a canadian build but I haven't quite figured out the best way to go about that.

**Comment by mbulut** [comment]
@stilor This breaks the toolchain build for me on a debian bullseye host.
In particular, it fails in the "Install C Library" step, saying that it could not find the target gcc.
Revision ba680a3 does not have that issue.
The toolchain config is attached.
[armv8-rpi3-linux-gnueabihf.txt](https://github.com/crosstool-ng/crosstool-ng/files/8064877/armv8-rpi3-linux-gnueabihf.txt)

**Comment by messense** [comment]
> In particular, it fails in the "Install C Library" step, saying that it could not find the target gc

Same issue, https://github.com/messense/homebrew-macos-cross-toolchains/actions/runs/1840835602

**Comment by stilor** [comment]
@mbulut  @messense You guys didn't run `ct-ng oldconfig` (or `ct-ng menuconfig`) after the update, did you? Some internal configuration variables have been changed due to unification of compiler passes, and your .configs have the _old_ variables in them. This is the reason the pass to build the target compiler was not done before ct-ng attempted to build the C library.

**Comment by cpackham** [comment]
@mbulut, @messense the problem with your failures is that the configs you are using need updating (your configs will say `CT_CC_CORE_PASS_1_NEEDED=y` but after these changes it needs to say `-CT_CC_CORE_NEEDED=y`). I was able to successfully build after running @mbulut 's config through `ct-ng oldconfig`.

**Comment by stilor** [comment]
@cpackham I actually think we should mark bionic obsolete. They dropped support for gcc some 3-4 years ago, which is why we have a quite old version of bionic in ct-ng. The patches to support bionic have not been ported to GCC11 (which is why I had to limit GCC selection for it to GCC10 and below). Frankly, I am not eager to port them - they have been a real pain to maintain in the past, as they are very invasive.

We should also mark obsolete glibc 2.12.1 (CentOS6 has reached EOL, I didn't want to obsolete it before that) and by extension, the whole glibc-ports package (of which 2.12.1 is the last remaining version). Maybe you have some other candidates for obsoletion, too?

After marking these obsolete, we should release 1.25.0 and remove the obsolete packages afterwards.

How does this plan sound?

**Comment by cpackham** [comment]
After I posted that I went and actually looked at it and now I'm all in favour of dropping bionic. It's probably not terribly useful to people wanting to develop for modern android-ndk and having it in ct-ng gives the impression that it's usable which it probably isn't. It also downloads binary images from the interwebs which is probably a bad idea.

Your plan sounds pretty good. Let's move the conversation over to #1477 (or a new issue if you want to start a fresh thread).

**Pull request merged**
