### PR TITLE
Apply patch for config.gcc to support e6500 to gcc4.9.3

### PR DESCRIPTION
**Pull request by ograff**
This resolves crosstool-ng/crosstool-ng#405

### CODE REVIEW

**Comment by ograff** [comment]
@bhundven updated!

**Comment by bhundven** [comment]
The branch is out of date, you need to update this pull request. See the README.md or ask if you need help.

**Comment by ograff** [comment]
Rebased on top of master, per the example in the README. Do you guys prefer rebases or merging master into the topic branch?

**Comment by stilor** [comment]
Rebases.

**Pull request merged**
