### PR TITLE
prefer default env: CT_LOCAL_TARBALLS_DIR

### PR DESCRIPTION
**Pull request by valord577**
refs https://github.com/crosstool-ng/crosstool-ng/pull/2196#issuecomment-2310830179

### CODE REVIEW

**Comment by valord577** [comment]
@cpackham Could you please take a time for code review?

**Comment by QBos07** [comment]
Great idea, but you are setting the variable to itself wich may not be obvious but Kconfig adds the `CT_` prefix. If you really need your env to be taken do it with this:
```sh
env >> .config
ct-ng build
```

It is  just `source .config` internally

**Comment by valord577** [comment]
> Great idea, but you are setting the variable to itself wich may not be obvious but Kconfig adds the `CT_` prefix. If you really need your env to be taken do it with this:
> 
> ```shell
> env >> .config
> ct-ng build
> ```
> 
> It is just `source .config` internally

@QBos07 

`CT_LOCAL_TARBALLS_DIR` is documented at https://crosstool-ng.github.io/docs/configuration/, but it is not really implemented.

image

**Comment by QBos07** [comment]
I think you understand the docs wrong. These aren't your normal environment variables (none on that site are), these are the configuration key names. You can look them up by pressing `?` on a specific configuration entry in `ct-ng menuconfig`. If you want to set config options you have to append them to `.config` or directly change the already existing entry in there. Everything documented at https://crosstool-ng.github.io/docs/configuration/ is only to be used from the inside of crosstool-ng!

Here is an slightly convoluted example of how to change the config at runtime: https://github.com/QBos07/CP-dockercross/blob/main/Dockerfile#L33. You can just write to the `.config` there directly

**Comment by valord577** [comment]
> I think you understand the docs wrong. 

@QBos07 Yeah, you are right. I does understand the docs wrong. Thank you very much for the detailed explanation. I will edit the `.config` file, then use it.

**Pull request closed without merging**
