### PR TITLE
Arm toolchain update

### PR DESCRIPTION
**Pull request by deece**
This pull request updates a number of dependent libraries to their latest versions (binutils, ISL, MPFR, GMP & Newlib).

### CODE REVIEW

**Comment by deece** [comment]
This obsoletes #481 and #371 (sorry, I didn't check before submitting this)

**Comment by stilor** [comment]
What about all the patches that we currently have? E.g. ones for binutils 2.26, newlib 2.1, etc. Are they all integrated upstream, or (as I suppose) you just didn't check?

**Comment by deece** [comment]
I took this branch against a recent master, so they should all be there. The 2 dependencies you mentioned (binutils 2.27 & newlib 2.1) are definitely already accounted for.

**Comment by stilor** [comment]
We do not have binutils 2.27 in master, so there is no patches in patches/binutils/2.27. We do have patches for binutils 2.26 in patches/binutils/2.26. Are all these patches picked up in 2.27? Did you check?

**Comment by deece** [comment]
Hmm, you're right, the patches did not apply. I'll review them for all the updated components. Is there anything else I should look out for?

**Comment by deece** [comment]
I've reviewed all the patches, remove the ones already upstreamed, and adjusted the ones that did not apply. I'll push my changes shortly.

**Comment by stilor** [comment]
A few general comments:
- I think @bhundven wanted to limit GCC selections to "last one in each stable branch". I.e., when adding GCC 6.3, remove GCC 6.2. I have no objections to keeping them both, so I'll let him decide.
- Please split off the commits for adding newlib options, LTO support and a new sample into a separate PR. Let's limit this one to pure upgrade.
- Which samples did you test the build with?

**Comment by bhundven** [comment]
If you look at [Gcc's website](https://gcc.gnu.org/), you will notice the `Supported Releases`.

Now look at: https://gcc.gnu.org/develop.html#timeline

In GCC 5, they changed their release structure to not handle minor revisions.

There is no longer a `gcc-5.1` branch for instance, just `gcc-5`, `gcc-6` branch.

Hence, gcc-6.3 is the latest supported release in the `gcc-6` branch, and gcc-6.2 is no longer supported upstream. If it is not supported upstream, I do not think it should be supported here.

**Comment by deece** [comment]
I've only tested with the arm-nano sample that I added (I expect that CI should test the important ones, but that may be a bad assumption)

**Comment by stilor** [comment]
It is a bad assumption indeed; Travis CI times out after 50 min on a configuration - which is not enough for some of them.

I'll try to pull your branch and test all the samples over the weekend.

**Comment by stilor** [comment]
Test suite ran through ~75% of the samples (I was testing my branch as well); so far no regressions. I expect the testing to finish tonight and then merge this tomorrow.

**Comment by stilor** [comment]
Also, I noticed that you didn't add any patches for the new releases of MPFR and GMP. Are all of these picked up upstream?

**Comment by deece** [comment]
Yup, MPFR & GMP patches are all upstream.

**Comment by stilor** [comment]
It had the regressions in the samples using GCC 4.x, e.g. in all `sh4-*` samples and `sparc-leon-linux-uclibc`:
````
[CFG  ]    checking for version 0.10 of ISL... no
[CFG  ]    checking for version 0.11 of ISL... no
[CFG  ]    checking for version 0.12 of ISL... no
[CFG  ]    checking for version 0.14 of ISL... no
[CFG  ]    checking for version 0.15 of ISL... no
[ERROR]    configure: error: Unable to find a usable ISL.  See config.log for details.
````
This should be fixed by adding a dependency on GCC5 for ISL 0.16.1.

It also breaks the xtensa sample with:
````
[ALL  ]    /home/aneyman/work/ctng/wc/.build/src/gcc-6.3.0/libgcc/config/xtensa/ieee754-sf.S: /home/aneyman/work/ctng/wc/.build/xtensa-fsf-linux-uclibc/build/build-cc-gcc-core-pass-2/./gcc/xgcc -B/home/aneyman/work/ctng/wc/.build/xtensa-fsf-linux-uclibc/build/build-cc-gcc-core-pass-2/./gcc/ -B/home/aneyman/work/ctng/wc/.build/xtensa-fsf-linux-uclibc/buildtools/xtensa-fsf-linux-uclibc/bin/ -B/home/aneyman/work/ctng/wc/.build/xtensa-fsf-linux-uclibc/buildtools/xtensa-fsf-linux-uclibc/lib/ -isystem /home/aneyman/work/ctng/wc/.build/xtensa-fsf-linux-uclibc/buildtools/xtensa-fsf-linux-uclibc/include -isystem /home/aneyman/work/ctng/wc/.build/xtensa-fsf-linux-uclibc/buildtools/xtensa-fsf-linux-uclibc/sys-include    -mlongcalls -mtext-section-literals -g -Os -O2  -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE  -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -fPIC -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector   -fPIC -I. -I. -I../.././gcc -I/home/aneyman/work/ctng/wc/.build/src/gcc-6.3.0/libgcc -I/home/aneyman/work/ctng/wc/.build/src/gcc-6.3.0/libgcc/. -I/home/aneyman/work/ctng/wc/.build/src/gcc-6.3.0/libgcc/../gcc -I/home/aneyman/work/ctng/wc/.build/src/gcc-6.3.0/libgcc/../include  -DHAVE_CC_TLS  -o _fixsfdi_s.o -MT _fixsfdi_s.o -MD -MP -MF _fixsfdi_s.dep -DSHARED -DL_fixsfdi -xassembler-with-cpp -c /home/aneyman/work/ctng/wc/.build/src/gcc-6.3.0/libgcc/config/xtensa/lib1funcs.S
[ALL  ]    Assembler messages:
[ALL  ]    /home/aneyman/work/ctng/wc/.build/src/gcc-6.3.0/libgcc/config/xtensa/ieee754-sf.S:237: Error: found ''', expected: ')'
[ALL  ]    /home/aneyman/work/ctng/wc/.build/src/gcc-6.3.0/libgcc/config/xtensa/ieee754-sf.S:237: Error: junk at end of line, first unrecognized character is `''
[ALL  ]    /home/aneyman/work/ctng/wc/.build/src/gcc-6.3.0/libgcc/config/xtensa/ieee754-sf.S:237: Internal error!
[ALL  ]    Assertion failure in ignore_rest_of_line at /home/aneyman/work/ctng/wc/.build/src/binutils-2.27/gas/read.c:3758.
[ALL  ]    Please report this bug.
[ALL  ]    Makefile:457: recipe for target '_addsubsf3_s.o' failed
````
No immediate advice here.

Are you going to look at fixing these? If not, I can pull your branch and try to fix these.

**Comment by stilor** [comment]
I can try that tomorrow. Thanks for the pointer to the xtensa fix.

**Pull request merged**
