### PR TITLE
Fix build-all

### PR DESCRIPTION
**Pull request by stilor**
- Properly use defconfig-style configurations: "copy+oldconfig" asks about all options not set by defconfig
- Handle canadian cross samples
- Order samples (canadian cross last, may need regular cross as a dependency)
- Do not abort the build-all on the first failed sample; instead, display the results for all samples in the end
- Fix show-config (display sample name consistent with what saveconfig would use) and rename one sample that did not follow saveconfig naming policy.

### CODE REVIEW

**Comment by stilor** [comment]
Result report looks as follows:
````
Success:
  - alphaev56-unknown-linux-gnu
  - alphaev67-unknown-linux-gnu
  - arm-bare_newlib_cortex_m3_nommu-eabi
  - arm-cortex_a15-linux-gnueabi
  - arm-cortexa5-linux-uclibcgnueabihf
  - arm-cortex_a8-linux-gnueabi
  - arm-cortexa9_neon-linux-gnueabihf
  - armeb-unknown-eabi
  - armeb-unknown-linux-gnueabi
  - armeb-unknown-linux-uclibcgnueabi
  - arm-unknown-eabi
  - arm-unknown-linux-gnueabi
  - arm-unknown-linux-musleabi
  - arm-unknown-linux-uclibcgnueabi
  - arm-unknown-linux-uclibcgnueabihf
  - armv6-rpi-linux-gnueabi
  - armv7-rpi2-linux-gnueabihf
  - avr
  - avr32-unknown-none
  - i586-geode-linux-uclibc
  - i686-nptl-linux-gnu
  - i686-w64-mingw32
  - i686-w64-mingw32,nios2-spico-elf
  - m68k-unknown-elf
  - m68k-unknown-uclinux-uclibc
  - mips64el-n32-linux-uclibc
  - mips64el-n64-linux-uclibc
  - mips-ar2315-linux-gnu
  - mipsel-sde-elf
  - mipsel-unknown-linux-gnu
  - mips-malta-linux-gnu
  - mips-unknown-elf
  - mips-unknown-linux-uclibc
  - powerpc-405-linux-gnu
  - powerpc64-unknown-linux-gnu
  - powerpc-860-linux-gnu
  - powerpc-e300c3-linux-gnu
  - powerpc-e500v2-linux-gnuspe
  - powerpc-unknown-linux-gnu
  - powerpc-unknown_nofpu-linux-gnu
  - s390-ibm-linux-gnu
  - s390x-ibm-linux-gnu
  - sh4-unknown-linux-gnu
  - sparc-unknown-linux-gnu
  - x86_64-unknown-linux-gnu
  - x86_64-unknown-linux-uclibc
  - x86_64-w64-mingw32

Expected failure:
  - i586-mingw32msvc,i686-none-linux-gnu
  - powerpc-unknown-linux-uclibc

Failure:
  - bfin-unknown-linux-uclibc
````

**Comment by bhundven** [comment]
@stilor what was the failure for bfin?

**Comment by stilor** [comment]
Some strange failure during 'installing GMP for host' stage; same failure in powerpc-unknown-linux-uclibc (i.e., it fails much earlier than it used to). The errors are from libtool - lots of them, starting with:

````
[ALL  ]    /bin/bash ../libtool --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I/home/avn/work/ctng/crosstool-ng/.build/src/gmp-4.3.2/mpn -I.. -D__GMP_WITHIN_GMP -I/home/avn/work/ctng/crosstool-ng/.build/src/gmp-4.3.2 -DOPERATION_`echo neg_n | sed 's/_$//'`    -O2 -g -pipe  -fexceptions -c -o neg_n.lo neg_n.c
[ALL  ]    ../libtool: line 386: s,^.*/,,g: No such file or directory
[ALL  ]    ../libtool: line 386: s,^.*/,,g: No such file or directory
[ALL  ]    ../libtool: line 386: s,^.*/,,g: No such file or directory
[ALL  ]    ../libtool: line 386: s,^.*/,,g: No such file or directory
[ALL  ]    ../libtool: line 386: s,^.*/,,g: No such file or directory
[ALL  ]    ../libtool: line 386: s,^.*/,,g: No such file or directory
[ALL  ]    ../libtool: line 386: s,^.*/,,g: No such file or directory
[ALL  ]    ../libtool: line 386: s,^.*/,,g: No such file or directory
[ALL  ]    ../libtool: line 386: s,^.*/,,g: No such file or directory
[ALL  ]    /home/avn/work/ctng/crosstool-ng/.build/bfin-unknown-linux-uclibc/build/build-gmp-host-x86_64-build_unknown-linux-gnu/mpn/../libtool: line 386: s,^.*/,,g: No such file or directory
[ALL  ]    /home/avn/work/ctng/crosstool-ng/.build/bfin-unknown-linux-uclibc/build/build-gmp-host-x86_64-build_unknown-linux-gnu/mpn/../libtool: line 386: s,^.*/,,g: No such file or directory
[ALL  ]    /home/avn/work/ctng/crosstool-ng/.build/bfin-unknown-linux-uclibc/build/build-gmp-host-x86_64-build_unknown-linux-gnu/mpn/../libtool: line 386: s,^.*/,,g: No such file or directory
[ALL  ]    /home/avn/work/ctng/crosstool-ng/.build/bfin-unknown-linux-uclibc/build/build-gmp-host-x86_64-build_unknown-linux-gnu/mpn/../libtool: line 386: s,^.*/,,g: No such file or directory
[ALL  ]    /home/avn/work/ctng/crosstool-ng/.build/bfin-unknown-linux-uclibc/build/build-gmp-host-x86_64-build_unknown-linux-gnu/mpn/../libtool: line 386: s,^.*/,,g: No such file or directory
[ALL  ]    /home/avn/work/ctng/crosstool-ng/.build/bfin-unknown-linux-uclibc/build/build-gmp-host-x86_64-build_unknown-linux-gnu/mpn/../libtool: line 386: s,^.*/,,g: No such file or directory
[ALL  ]    /home/avn/work/ctng/crosstool-ng/.build/bfin-unknown-linux-uclibc/build/build-gmp-host-x86_64-build_unknown-linux-gnu/mpn/../libtool: line 386: s,^.*/,,g: No such file or directory
[ALL  ]    /home/avn/work/ctng/crosstool-ng/.build/bfin-unknown-linux-uclibc/build/build-gmp-host-x86_64-build_unknown-linux-gnu/mpn/../libtool: line 386: s,^.*/,,g: No such file or directory
[ALL  ]    /home/avn/work/ctng/crosstool-ng/.build/bfin-unknown-linux-uclibc/build/build-gmp-host-x86_64-build_unknown-linux-gnu/mpn/../libtool: line 386: s,^.*/,,g: No such file or directory
[ALL  ]    /home/avn/work/ctng/crosstool-ng/.build/bfin-unknown-linux-uclibc/build/build-gmp-host-x86_64-build_unknown-linux-gnu/mpn/../libtool: line 779: X--mode=compile: command not found
[ALL  ]    /home/avn/work/ctng/crosstool-ng/.build/bfin-unknown-linux-uclibc/build/build-gmp-host-x86_64-build_unknown-linux-gnu/mpn/../libtool: line 779: -e: command not found
[ALL  ]    /home/avn/work/ctng/crosstool-ng/.build/bfin-unknown-linux-uclibc/build/build-gmp-host-x86_64-build_unknown-linux-gnu/mpn/../libtool: line 779: X--mode=compile: command not found
````

Something seems to have changed on master;

**Comment by bhundven** [comment]
I find this strange, because it is just fine in the latest build: https://travis-ci.org/crosstool-ng/crosstool-ng/builds/88226521 from the latest commit.

**Comment by stilor** [comment]
Yeah, just tried building via regular sequence (./ct-ng 
bfin-unknown-linux-uclibc; ./ct-ng build) and it builds fine. Something 
else is different in build-all, it seems - don't pull this yet, I'll 
find what.

**Comment by stilor** [comment]
Try

````
./ct-ng bfin-unknown-linux-uclibc
./ct-ng build V=0
````

You're in for a surprise :)

**Comment by bhundven** [comment]
@mingwandroid @diorcety @yann-morin-1998 - I've looked over these changes a few times, and nothing pops out at me. Would at least one of you do a quick review of these changes?

**Pull request merged**
