### PR TITLE
Unbreak nios2-elf-mingw32 sample

### PR DESCRIPTION
**Pull request by stilor**
Do not use non-CT environment variables in the config (by default, the sample tries to write into build system's root). Disable with-system-zlib and cross-gdb (for now); see the commit messages for details.

### CODE REVIEW

**Comment by bhundven** [comment]
I would suggest doing the promotion in a separate PR, and we'll get back to this one after we know that the promotion of expat and ncurses didn't break anything.

Also, I noticed (I'm not hip with the times as much as I should be) that ncurses 6 is out. Maybe we should update that as well. I'm still unsure if we need to stick with the ncurses 5 ABI, or if gdb will work with the new ncurses 6 ABI? That might be a point of experimentation (with some prior versions of gdb). But also keep in mind issues like #222 where I am going to start trimming older versions of gdb as well. (I still need to open an issue on that)

**Comment by stilor** [comment]
I agree with a separate PR for expat/ncurses changes, but I think this change should not be held up by that task. See, this sample had other breakages in addition to expat/ncurses issue, so I don't want this sample to get broken further while the "promotion" is being worked on. Once expat/ncurses are done, we can always re-enable cross-gdb in this sample, just as we did with ltrace.

**Comment by bhundven** [comment]
Fair enough. Merged. Thanks! I'm guessing you are going to work on the promotion? Or should I do that?

**Comment by stilor** [comment]
I can work on that.

**Comment by bhundven** [comment]
@stilor cool. Thanks! Let me know if you need help!

**Pull request merged**
