### PR TITLE
gcc: Add GCC 12.1 release

### PR DESCRIPTION
**Pull request by cmuellner**
This adds the GCC 12.1 release.
Tested with RISC-V RV64GC.

The GCC build script needed to be adjusted to overcome the following issue with GCC 12:
```
[ERROR]    make[1]: *** No rule to make target '../build-x86_64-build_pc-linux-gnu/libcpp/libcpp.a', needed by 'build/genmatch'.  Stop.
```

Built compiler version:
```
riscv64-unknown-linux-gnu-gcc (crosstool-NG 1.25.0.24_d457e27) 12.1.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### CODE REVIEW

**Comment by cmuellner** [comment]
Also tested a build of GCC 4.9.4 (starting with `x86_64-centos6-linux-gnu` and selecting the oldest versions of Binutilis, glibc, and GCC):

```
$ ./x86_64-centos6-linux-gnu/bin/x86_64-centos6-linux-gnu-gcc -v
Using built-in specs.
COLLECT_GCC=./x86_64-centos6-linux-gnu/bin/x86_64-centos6-linux-gnu-gcc
COLLECT_LTO_WRAPPER=/home/cm/src/crosstool-ng/gcc12-gcc4/x86_64-centos6-linux-gnu/libexec/gcc/x86_64-centos6-linux-gnu/4.9.4/lto-wrapper
Target: x86_64-centos6-linux-gnu
Configured with: /home/cm/src/crosstool-ng/gcc12-gcc4/.build/x86_64-centos6-linux-gnu/src/gcc/configure --build=x86_64-build_pc-linux-gnu --host=x86_64-build_pc-linux-gnu --target=x86_64-centos6-linux-gnu --prefix=/home/cm/src/crosstool-ng/gcc12-gcc4/x86_64-centos6-linux-gnu --exec_prefix=/home/cm/src/crosstool-ng/gcc12-gcc4/x86_64-centos6-linux-gnu --with-sysroot=/home/cm/src/crosstool-ng/gcc12-gcc4/x86_64-centos6-linux-gnu/x86_64-centos6-linux-gnu/sysroot --enable-languages=c,c++ --with-pkgversion='crosstool-NG 1.25.0.24_69cb750' --enable-__cxa_atexit --disable-tm-clone-registry --disable-libmudflap --disable-libgomp --disable-libssp --disable-libquadmath --disable-libquadmath-support --disable-libsanitizer --disable-libstdcxx-verbose --with-gmp=/home/cm/src/crosstool-ng/gcc12-gcc4/.build/x86_64-centos6-linux-gnu/buildtools --with-mpfr=/home/cm/src/crosstool-ng/gcc12-gcc4/.build/x86_64-centos6-linux-gnu/buildtools --with-mpc=/home/cm/src/crosstool-ng/gcc12-gcc4/.build/x86_64-centos6-linux-gnu/buildtools --with-isl=/home/cm/src/crosstool-ng/gcc12-gcc4/.build/x86_64-centos6-linux-gnu/buildtools --with-cloog=/home/cm/src/crosstool-ng/gcc12-gcc4/.build/x86_64-centos6-linux-gnu/buildtools --enable-lto --without-zstd --with-host-libstdcxx='-static-libgcc -Wl,-Bstatic,-lstdc++,-Bdynamic -lm' --enable-threads=posix --enable-target-optspace --disable-plugin --disable-nls --disable-multilib --with-local-prefix=/home/cm/src/crosstool-ng/gcc12-gcc4/x86_64-centos6-linux-gnu/x86_64-centos6-linux-gnu/sysroot --enable-long-long
Thread model: posix
gcc version 4.9.4 (crosstool-NG 1.25.0.24_69cb750)
```

**Comment by cpackham** [comment]
Clashes with #1730 but I like your resolution for the genmatch issue better than mine. I also expect this will hit the same sh-unknown-elf mutlilib issue I've been seeing. I'll incorporate your script change into my PR.

**Comment by cmuellner** [comment]
Ok, sounds good!

**Comment by cpackham** [comment]
Merged #1730 so closing this unmerged.

**Pull request closed without merging**
