### PR TITLE
Add glibc 2.30

### PR DESCRIPTION
**Pull request by cpackham**
Add the GNU C Library version 2.30. Bring forward the
typedef-caddr.patch. Skip the ARC patch for now.

https://sourceware.org/ml/libc-alpha/2019-08/msg00029.html

Signed-off-by: Chris Packham <judge.packham@gmail.com>

### CODE REVIEW

**Comment by abrodkin** [comment]
Even though @stilor was not happy with ARC changes not being a part of upstream release and we had an expectation to become a part of 2.30 but again (due to completely non-technical issues) we missed upstream release. So look like to bridge the gap until Glibc 2.31 (which we're targeting now) we'll need yet another patch for ARC which I may prepare in no time.

Do you want it to be incorporated in this pull-request?

**Comment by cpackham** [comment]
@abrodkin I'd be happy to include ARC support in this PR. I just wasn't going to attempt to migrate the patch myself. If you get a patch/commit somewhere I can fetch it I'll happily add it.

**Comment by abrodkin** [comment]
@cpackham feel free to grab updated patch for ARC from here - https://github.com/abrodkin/crosstool-ng/commit/fb1736fb488ec51e77c7d9b2ee271ae3f93715fc.

Note it has a fix mentioned here https://github.com/crosstool-ng/crosstool-ng/pull/1233#issuecomment-528816808.

Proven to build with:
```
./ct-ng arc-archs-linux-gnu
./ct-ng build
```

See:
```
# ~/x-tools/arc-snps-linux-gnu/bin/arc-linux-gcc -v
Using built-in specs.
COLLECT_GCC=.../x-tools/arc-snps-linux-gnu/bin/arc-linux-gcc
COLLECT_LTO_WRAPPER=.../x-tools/arc-snps-linux-gnu/bin/../libexec/gcc/arc-snps-linux-gnu/8.3.0/lto-wrapper
Target: arc-snps-linux-gnu
Configured with: .../crosstool-ng/.build/arc-snps-linux-gnu/src/gcc/configure --build=x86_64-build_pc-linux-gnu --host=x86_64-build_pc-linux-gnu --target=arc-snps-linux-gnu --prefix=.../x-tools/arc-snps-linux-gnu --with-sysroot=.../x-tools/arc-snps-linux-gnu/arc-snps-linux-gnu/sysroot --enable-languages=c --with-cpu=archs --with-pkgversion='crosstool-NG 1.24.0.8-9dad044' --enable-__cxa_atexit --disable-libmudflap --disable-libgomp --disable-libssp --disable-libquadmath --disable-libquadmath-support --disable-libsanitizer --disable-libmpx --with-gmp=.../crosstool-ng/.build/arc-snps-linux-gnu/buildtools --with-mpfr=.../crosstool-ng/.build/arc-snps-linux-gnu/buildtools --with-mpc=.../crosstool-ng/.build/arc-snps-linux-gnu/buildtools --with-isl=.../crosstool-ng/.build/arc-snps-linux-gnu/buildtools --enable-lto --enable-threads=posix --enable-target-optspace --disable-plugin --disable-nls --disable-multilib --with-local-prefix=.../x-tools/arc-snps-linux-gnu/arc-snps-linux-gnu/sysroot --enable-long-long
Thread model: posix
gcc version 8.3.0 (crosstool-NG 1.24.0.8-9dad044)
```

**Comment by bhundven** [comment]
See my comment from: https://github.com/crosstool-ng/crosstool-ng/pull/1233

**Pull request merged**
