### PR TITLE
Add travis continuous integration system

### PR DESCRIPTION
**Pull request by jmlemetayer**
For now I have selected this standard samples:

 * arm-unknown-eabi
 * armeb-unknown-eabi
 * arm-unknown-linux-gnueabi
 * armeb-unknown-linux-gnueabi

I think it's a good start. We could add the other later.

### CODE REVIEW

**Comment by bhundven** [comment]
Yeay to testing!

**Comment by jasmin-j** [comment]
I have seen you have already activated the travis-ci tests.
I like this really much. This would have found all the issues with isl 0.15 and ClooG.

Did you activate travis-ci for pushes only or for pull requests, too?

**Comment by bhundven** [comment]
Pull requests as well.

**Comment by bhundven** [comment]
The build failed.

**Comment by jasmin-j** [comment]
I have seen it. But not all selected samples.
They failed at building GDB
  ../lib/libncurses.a: could not read symbols: Archive has no index; run ranlib to add one
I will check if this builds on my machine. If yes, it is an issue with travis-ci.
If no it might be the GDB version or something else.

**Comment by jasmin-j** [comment]
I passed native gdb on my machine, but then I got:
[ALL  ]    /bin/bash ./libtool --tag=CC   --mode=link arm-unknown-linux-gnueabi-gcc -Wall -Wsign-compare -Wfloat-equal -Wformat-security -Werror -g -O2   -o ltrace     main.o libltrace.la -lelf
 [ALL  ]    libtool: link: arm-unknown-linux-gnueabi-gcc -Wall -Wsign-compare -Wfloat-equal -Wformat-security -Werror -g -O2 -o ltrace main.o  ./.libs/libltrace.a -lelf
 [ALL  ]    ./.libs/libltrace.a(demangle.o): In function `my_demangle':
 [ALL  ]    /home/jasmin/SW/crosstool-ng/crosstool-ng/.build/arm-unknown-linux-gnueabi/build/build-ltrace/demangle.c:55: undefined reference to `__cxa_demangle'
 [ERROR]    collect2: error: ld returned 1 exit status
 [ERROR]    make[4]: *** [ltrace] Error 1
 [ALL  ]    make[4]: Leaving directory `/home/jasmin/SW/crosstool-ng/crosstool-ng/.build/arm-unknown-linux-gnueabi/build/build-ltrace'
 [ERROR]    make[3]: *** [all-recursive] Error 1
 [ALL  ]    make[3]: Leaving directory `/home/jasmin/SW/crosstool-ng/crosstool-ng/.build/arm-unknown-linux-gnueabi/build/build-ltrace'
 [ERROR]    make[2]: *** [all] Error 2
 [ALL  ]    make[2]: Leaving directory `/home/jasmin/SW/crosstool-ng/crosstool-ng/.build/arm-unknown-linux-gnueabi/build/build-ltrace'
 [ERROR]
 [ERROR]  >>
 [ERROR]  >>  Build failed in step 'Installing ltrace'
 [ERROR]  >>        called in step '(top-level)'
 [ERROR]  >>
 [ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@257]
 [ERROR]  >>        called from: do_debug_ltrace_build[scripts/build/debug/400-ltrace.sh@55]
 [ERROR]  >>        called from: do_debug[scripts/build/debug.sh@35]
 [ERROR]  >>        called from: main[scripts/crosstool-NG.sh@638]
 [ERROR]  >>
 [ERROR]  >>  For more info on this error, look at the file: 'build.log'
 [ERROR]  >>  There is a list of known issues, some with workarounds, in:
 [ERROR]  >>      'docs/B - Known issues.txt'
 [ERROR]
 [ERROR]  (elapsed: 71:28.08)

grep results:
jasmin@CAT ~/x-tools/arm-unknown-linux-gnueabi $ grep -r cxa_demangle *
Binary file arm-unknown-linux-gnueabi/bin/ld.gold matches
arm-unknown-linux-gnueabi/include/c++/5.2.0/cxxabi.h:  __cxa_demangle(const char* __mangled_name, char* __output_buffer,
Binary file arm-unknown-linux-gnueabi/sysroot/lib/libstdc++.so.6.0.21 matches
Binary file arm-unknown-linux-gnueabi/sysroot/lib/libstdc++.a matches
Binary file arm-unknown-linux-gnueabi/sysroot/lib/libsupc++.a matches
Binary file bin/arm-unknown-linux-gnueabi-gcc matches
Binary file bin/arm-unknown-linux-gnueabi-c++ matches
Binary file bin/arm-unknown-linux-gnueabi-cpp matches
Binary file bin/arm-unknown-linux-gnueabi-dwp matches
Binary file bin/arm-unknown-linux-gnueabi-ld.gold matches
Binary file bin/arm-unknown-linux-gnueabi-gcov matches
Binary file bin/arm-unknown-linux-gnueabi-gcc-5.2.0 matches
Binary file bin/arm-unknown-linux-gnueabi-g++ matches
Binary file bin/arm-unknown-linux-gnueabi-gcov-tool matches
Binary file libexec/gcc/arm-unknown-linux-gnueabi/5.2.0/lto-wrapper matches
Binary file libexec/gcc/arm-unknown-linux-gnueabi/5.2.0/cc1plus matches
Binary file libexec/gcc/arm-unknown-linux-gnueabi/5.2.0/lto1 matches
Binary file libexec/gcc/arm-unknown-linux-gnueabi/5.2.0/cc1 matches
Binary file libexec/gcc/arm-unknown-linux-gnueabi/5.2.0/collect2 matches

ltrace configure check:
 [CFG  ]    checking for cplus_demangle in -liberty... no
 [CFG  ]    checking for __cxa_demangle in -lsupc++... yes
 [CFG  ]    checking for __cxa_demangle in -lstdc++... yes

@bhundven
Any idea why ltrace doesn't link with one of the C++ libraries?

**Comment by jmlemetayer** [comment]
FYI travis-ci use Ubuntu 12.04 LTS Server Edition 64 bit virtual
machines (http://docs.travis-ci.com/user/ci-environment/). So the host
tools version is not the same as yours.

At the top of the travis log
(https://travis-ci.org/crosstool-ng/crosstool-ng/jobs/81661423) you
can see in the `system_info` section the GCC version used: "gcc
(Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3"

Maybe this can explain the first issue with GDB.

2015-09-23 1:13 GMT+02:00 Jasmin Jessich <notifications@github.com>:

**Comment by jasmin-j** [comment]
@bhundven 
I have now done the build with ltrace-0.5.3 and this worked.
It might be this change d90a3c0ca5284e929f95f61b1c80b473233bc3cc . ltrace 0.7.3 was added
with commit 4f4c3875 (Daniel Zimmermann 2014-02-19 22:36:03 +0100 18), so I am sure it worked
before the Debian patch syncing. Maybe you need to check the patches again.

The build took 73:44 minutes, which is far too long for travis-ci. It might be, that travis-ci has a faster
machine, but if not we need to remove the Linux samples from the list of test samples.

I will now NOT dig into the gdb ncurses problem, because it is difficult to debug (need a machine
with the exact same Debian version) and the build will fail for the native gdb, which is built for the
Linux targets only, I guess. And we will remove these targets anyway due to lack of build time.
When you have your Jenkins machine, I am sure you will install a newer build system (Ubuntu
Server) and then this targets can be tested there.

Successfull build output:
[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20150923.020757
[INFO ]  Building environment variables
[EXTRA]  Preparing working directories
[EXTRA]  Installing user-supplied crosstool-NG configuration
[EXTRA]  =================================================================
[EXTRA]  Dumping internal crosstool-NG configuration
[EXTRA]    Building a toolchain for:
[EXTRA]      build  = x86_64-unknown-linux-gnu
[EXTRA]      host   = x86_64-unknown-linux-gnu
[EXTRA]      target = arm-unknown-linux-gnueabi
[EXTRA]  Dumping internal crosstool-NG configuration: done in 0.10s (at 00:03)
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[EXTRA]    Retrieving 'ltrace_0.5.3.orig'
[EXTRA]    Saving 'ltrace_0.5.3.orig.tar.gz' to local storage
[INFO ]  Retrieving needed toolchain components' tarballs: done in 1.14s (at 00:04)
[INFO ]  =================================================================
[INFO ]  Extracting and patching toolchain components
[EXTRA]    Extracting 'linux-4.2'
[EXTRA]    Patching 'linux-4.2'
[EXTRA]    Extracting 'gmp-6.0.0a'
[EXTRA]    Patching 'gmp-6.0.0a'
[EXTRA]    Extracting 'mpfr-3.1.3'
[EXTRA]    Patching 'mpfr-3.1.3'
[EXTRA]    Extracting 'isl-0.14'
[EXTRA]    Patching 'isl-0.14'
[EXTRA]    Extracting 'mpc-1.0.3'
[EXTRA]    Patching 'mpc-1.0.3'
[EXTRA]    Extracting 'libelf-0.8.13'
[EXTRA]    Patching 'libelf-0.8.13'
[EXTRA]    Extracting 'binutils-2.25.1'
[EXTRA]    Patching 'binutils-2.25.1'
[EXTRA]    Extracting 'gcc-5.2.0'
[EXTRA]    Patching 'gcc-5.2.0'
[EXTRA]    Extracting 'glibc-2.22'
[EXTRA]    Patching 'glibc-2.22'
[EXTRA]    Extracting 'dmalloc-5.5.2'
[EXTRA]    Patching 'dmalloc-5.5.2'
[EXTRA]    Extracting 'duma_2_5_15'
[EXTRA]    Patching 'duma-2_5_15'
[EXTRA]    Extracting 'gdb-7.10'
[EXTRA]    Patching 'gdb-7.10'
[EXTRA]    Extracting 'ncurses-5.9'
[EXTRA]    Patching 'ncurses-5.9'
[EXTRA]    Extracting 'expat-2.1.0'
[EXTRA]    Patching 'expat-2.1.0'
[EXTRA]    Extracting 'ltrace-0.5.3'
[EXTRA]    Patching 'ltrace-0.5.3'
[EXTRA]    Extracting 'strace-4.10'
[EXTRA]    Patching 'strace-4.10'
[INFO ]  Extracting and patching toolchain components: done in 72.73s (at 01:17)
[EXTRA]  Saving state to restart at step 'libc_check_config'...
[EXTRA]  Saving state to restart at step 'companion_libs_for_build'...
[EXTRA]  Saving state to restart at step 'binutils_for_build'...
[EXTRA]  Saving state to restart at step 'companion_libs_for_host'...
[INFO ]  =================================================================
[INFO ]  Installing GMP for host
[EXTRA]    Configuring GMP
[EXTRA]    Building GMP
[EXTRA]    Installing GMP
[INFO ]  Installing GMP for host: done in 59.23s (at 02:17)
[INFO ]  =================================================================
[INFO ]  Installing MPFR for host
[EXTRA]    Configuring MPFR
[EXTRA]    Building MPFR
[EXTRA]    Installing MPFR
[INFO ]  Installing MPFR for host: done in 48.66s (at 03:06)
[INFO ]  =================================================================
[INFO ]  Installing ISL for host
[EXTRA]    Configuring ISL
[EXTRA]    Building ISL
[EXTRA]    Installing ISL
[INFO ]  Installing ISL for host: done in 41.65s (at 03:47)
[INFO ]  =================================================================
[INFO ]  Installing MPC for host
[EXTRA]    Configuring MPC
[EXTRA]    Building MPC
[EXTRA]    Installing MPC
[INFO ]  Installing MPC for host: done in 20.75s (at 04:08)
[EXTRA]  Saving state to restart at step 'binutils_for_host'...
[INFO ]  =================================================================
[INFO ]  Installing binutils for host
[EXTRA]    Configuring binutils
[EXTRA]    Building binutils
[EXTRA]    Installing binutils
[EXTRA]    Installing ld wrapper
[INFO ]  Installing binutils for host: done in 307.12s (at 09:16)
[EXTRA]  Saving state to restart at step 'cc_core_pass_1'...
[INFO ]  =================================================================
[INFO ]  Installing pass-1 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[EXTRA]    Installing gcc
[INFO ]  Installing pass-1 core C gcc compiler: done in 639.09s (at 20:02)
[EXTRA]  Saving state to restart at step 'kernel_headers'...
[INFO ]  =================================================================
[INFO ]  Installing kernel headers
[EXTRA]    Installing kernel headers
[EXTRA]    Checking installed headers
[INFO ]  Installing kernel headers: done in 13.52s (at 20:31)
[EXTRA]  Saving state to restart at step 'libc_start_files'...
[INFO ]  =================================================================
[INFO ]  Installing C library headers & start files
[EXTRA]    Configuring C library
[EXTRA]    Installing C library headers
[EXTRA]    Installing C library start files
[INFO ]  Installing C library headers & start files: done in 17.42s (at 21:04)
[EXTRA]  Saving state to restart at step 'cc_core_pass_2'...
[INFO ]  =================================================================
[INFO ]  Installing pass-2 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[EXTRA]    Installing gcc
[INFO ]  Installing pass-2 core C gcc compiler: done in 802.40s (at 34:41)
[EXTRA]  Saving state to restart at step 'libc'...
[INFO ]  =================================================================
[INFO ]  Installing C library
[EXTRA]    Configuring C library
[EXTRA]    Building C library
[EXTRA]    Installing C library
[INFO ]  Installing C library: done in 490.03s (at 43:07)
[EXTRA]  Saving state to restart at step 'cc_for_build'...
[EXTRA]  Saving state to restart at step 'cc_for_host'...
[INFO ]  =================================================================
[INFO ]  Installing final gcc compiler
[EXTRA]    Configuring final gcc compiler
[EXTRA]    Building final gcc compiler
[EXTRA]    Installing final gcc compiler
[INFO ]  Installing final gcc compiler: done in 936.37s (at 59:17)
[EXTRA]  Saving state to restart at step 'libc_post_cc'...
[EXTRA]  Saving state to restart at step 'libelf_for_target'...
[INFO ]  =================================================================
[INFO ]  Installing libelf for the target
[EXTRA]    Configuring libelf
[EXTRA]    Building libelf
[EXTRA]    Installing libelf
[INFO ]  Installing libelf for the target: done in 6.30s (at 60:25)
[EXTRA]  Saving state to restart at step 'binutils_for_target'...
[EXTRA]  Saving state to restart at step 'debug'...
[INFO ]  =================================================================
[INFO ]  Installing dmalloc
[EXTRA]    Configuring dmalloc
[EXTRA]    Building dmalloc
[EXTRA]    Installing dmalloc
[INFO ]  Installing dmalloc: done in 11.62s (at 61:37)
[INFO ]  =================================================================
[INFO ]  Installing D.U.M.A.
[EXTRA]    Copying sources
[EXTRA]    Building libraries 'libduma.a libduma.so.0.0.0'
[EXTRA]    Installing libraries 'libduma.a libduma.so.0.0.0'
[EXTRA]    Installing shared library link
[EXTRA]    Installing wrapper script
[INFO ]  Installing D.U.M.A.: done in 1.44s (at 61:39)
[INFO ]  =================================================================
[INFO ]  Installing cross-gdb
[EXTRA]    Configuring cross-gdb
[EXTRA]    Building cross-gdb
[EXTRA]    Installing cross-gdb
[EXTRA]    Installing '.gdbinit' template
[INFO ]  Installing cross-gdb: done in 227.54s (at 65:26)
[INFO ]  =================================================================
[INFO ]  Installing native gdb
[EXTRA]    Building static target ncurses
[EXTRA]    Building static target expat
[EXTRA]    Configuring native gdb
[EXTRA]    Building native gdb
[EXTRA]    Installing native gdb
[INFO ]  Installing native gdb: done in 310.45s (at 70:37)
[INFO ]  =================================================================
[INFO ]  Installing gdbserver
[EXTRA]    Configuring gdbserver
[EXTRA]    Building gdbserver
[EXTRA]    Installing gdbserver
[INFO ]  Installing gdbserver: done in 71.71s (at 71:49)
[INFO ]  =================================================================
[INFO ]  Installing ltrace
[EXTRA]    Copying sources to build dir
[EXTRA]    Configuring ltrace
[EXTRA]    Building ltrace
[EXTRA]    Installing ltrace
[INFO ]  Installing ltrace: done in 3.25s (at 71:52)
[INFO ]  =================================================================
[INFO ]  Installing strace
[EXTRA]    Configuring strace
[EXTRA]    Building strace
[EXTRA]    Installing strace
[INFO ]  Installing strace: done in 47.21s (at 72:39)
[EXTRA]  Saving state to restart at step 'test_suite'...
[EXTRA]  Saving state to restart at step 'finish'...
[INFO ]  =================================================================
[INFO ]  Cleaning-up the toolchain's directory
[INFO ]    Stripping all toolchain executables
[EXTRA]    Installing the populate helper
[EXTRA]    Installing a cross-ldd helper
[EXTRA]    Creating toolchain aliases
[EXTRA]    Removing access to the build system tools
[INFO ]  Cleaning-up the toolchain's directory: done in 1.55s (at 73:44)
[INFO ]  Build completed at 20150923.032140
[INFO ]  (elapsed: 73:43.70)
[INFO ]  Finishing installation (may take a few seconds)...
[73:44] / jasmin@CAT ~/SW/crosstool-ng/crosstool-ng $

**Comment by jasmin-j** [comment]
> So the host tools version is not the same as yours. ...
> ... section the GCC version used: "gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3"

I am building with" gcc (Ubuntu/Linaro 4.8.1-10ubuntu9) 4.8.1" and had no problem.

The cross GDB runs on the host and can debug code for the target.
The native GDB runs on the target and can debug code for this target.
For my understanding ... shouldn't the native GDB build with the just built cross-gcc? This means it
should be completely independent from any tool versions on the host.
I can't believe CT-NG will use the wrong tools to compile the native GDB. Such a profound error
would have been detected earlier.

**Comment by jmlemetayer** [comment]
I have tested on my Ubuntu server 14.04 with GCC 4.8.4 and I pass the native GDB also (it also fail during the ltrace step).

I think I have found something. Here the failing trace from travis:

    [ALL  ]    gcc -O2 --param max-inline-insns-single=1200  -o background ../objects/background.o  -I. -I/home/travis/build/crosstool-ng/crosstool-ng/.build/src/ncurses-5.9/test -I../test -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include -I/home/travis/build/crosstool-ng/crosstool-ng/.build/src/ncurses-5.9/test/../include -I/home/travis/build/crosstool-ng/crosstool-ng/.build/arm-unknown-linux-gnueabi/build/static-target/include/ncurses -O2 --param max-inline-insns-single=1200  `echo "-static -L../lib -lform -lmenu -lpanel -lncurses  -dynamic  " | sed -e 's/-lform.*-lpanel[^ ]*//'` -lutil  -lm

And here is my passing trace:

    [ALL  ]    arm-unknown-linux-gnueabi-gcc -O2 --param max-inline-insns-single=1200  -o background ../objects/background.o  -I. -I/home/jmlemetayer/crosstool-ng/github/.build/src/ncurses-5.9/test -I../test -DHAVE_CONFIG_H  -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64  -DNDEBUG -I. -I../include -I/home/jmlemetayer/crosstool-ng/github/.build/src/ncurses-5.9/test/../include -I/home/jmlemetayer/crosstool-ng/github/.build/arm-unknown-linux-gnueabi/build/static-target/include/ncurses -O2 --param max-inline-insns-single=1200  `echo "-static -L../lib -lform -lmenu -lpanel -lncurses  -dynamic  " | sed -e 's/-lform.*-lpanel[^ ]*//'` -lutil  -lm


The differences are:

 * The compiler: `gcc` vs `arm-unknown-linux-gnueabi-gcc`
 * A define: `-D_FILE_OFFSET_BITS=64`

So, I wanted to check the ncurses configuration but the log is too short ...

Maybe we have to display the whole `build.log` instead of the 200 last lines to deal with such cases.

**Comment by jasmin-j** [comment]
Yeah, you found it!
When you look to the output, you will see:
  $ export CC=gcc
I guess this comes from this line in .travis.yml:
  compiler: gcc

I will fix that this evening.

**Comment by jasmin-j** [comment]
Fixed with pull request #186.
The build will still fail for Linux targets, but this is the issue with ltrace and needs to be fixed by
someone else.

**Comment by jasmin-j** [comment]
I guess we can close this now.

**Pull request merged**
