### PR TITLE
fix bashisms in patch-rework.sh script

### PR DESCRIPTION
**Pull request by Ledest**
Signed-off-by: Led <ledest@gmail.com>

### CODE REVIEW

**Comment by bhundven** [comment]
@Ledest As I mentioned in: #17 ... is there some error you are getting or a specific reason you have posted the changes. The changes result in effectively the same results. I don't see any problems with your change, I just don't see why it is nessasary. The 'git log' should also reflect that description.

On a secondary note, you don't need to close a pull request and open a new one. The trick is to just force push the updated change to your repository/branch and click the pull request button again. It will update the pull request you already have. :)
That way we also keep the review in tact instead of having to reference the previous pull request (as I did above).

**Comment by Ledest** [comment]
> I just don't see why it is nessasary.

patch-rework.sh is the shell script (with /bin/sh shebang). But it contain bash-specific constructions ("pushd/popd", "for((...))", "read" with '-u' options). These constructions can easily be replaces to standard POSIX-shell's constructions. Or, in other words, "fix bashisms in shell script".

**Comment by bhundven** [comment]
Ok, so with that in mind and considering that 70% (63.51% of all statistics are made up on the spot ;) ) of the scripts on crosstool-NG are bash (with /bin/bash shebang), would it make more sense to just change the shebang and call it good? I ask this because we do have a requirement to have a recent bash installed. Again, I still don't see anything wrong with the patch, and I have no problem keeping this one script posix, but I have to play the devils advocate.

**Comment by Ledest** [comment]
> considering that 70% of the scripts on crosstool-NG are bash (with /bin/bash shebang), would it make more sense to just change the shebang and call it good?

May be - you know better. I try fix one particular shell script only.

**Comment by bhundven** [comment]
On Fri, Jan 2, 2015 at 10:51 AM, Led <notifications@github.com> wrote:

> considering that 70% of the scripts on crosstool-NG are bash (with
> /bin/bash shebang), would it make more sense to just change the shebang and
> call it good?
>
> May be - you know better. I try fix one particular shell script only.
>
Not trying to sound confusing, but it's possible that these scripts are
supposed to be posix shell scripts for a reason, and somehow (I'm sure git
log can tell us) bashism's have slipped in on accident. @yann-morin-1998 Do
you know if that is the case?

If we fix bashism's in patch-rework.sh, should we also either switch the
shabang or update others in scripts/ dir?

For instanace, here is a short list of ```#!/bin/sh``` files in the scripts
directory:

```
addToolVersion.sh
get_in_frags.sh
install.sh (which is ok to be /bin/sh)
patch-renumber.sh
patch-rework.sh (this one)
showSamples.sh
```

If the shebang moves to /bin/bash, then should we rename these files to
${scriptname}.sh.in so that if the user has bash in /usr/local/bin or
/opt/bash/bin (and in their PATH env) the shabang points to the right place:

Such as from: crosstool-NG.sh.in
```
#!@@CT_bash@@
```

**Comment by yann-morin-1998** [comment]
AS discussed with Bryan on IRC: bashisms may have sneaked in by accident.

When I wrote that script years ago, I also did not use it from a confiogure crosstool-NG tree, so I did not use the usual `@@CT_bash@@` like for other scripts, and just used the default shell.

But at that time, I was not as careful about POSIXly correctness as I am (trying to be) now.

So yes, the patch looks sane. Don't bother about my comment about the alternate addition, I was just bragging a bit. ;-)

Regards,
Yann E. MORIN.

**Comment by bhundven** [comment]
With that... I'm happy to accept the patch, but I'd like to see the commit description has more then "fix bashism's". If you can update it in your local repository, and click the pull request button again to update this pull request, I'll accept the patch. (no need to make a new pull request ;) )

**Comment by bhundven** [comment]
Again, All I want before I apply this patch is the commit description updated to just say something along the lines of what the patch does, i.e.: "This script has a '#!/bin/sh' shabang and might be running on a posix shell. Over time some bash features have slipped in and need to be removed."

git clone git@github.com:Ledest/crosstool-ng
cd crosstool-ng
git commit --amend
<update commit message>
git push --force

Then just hit the pull request button on your clone again and you don't need to close this pull request and just update this one instead.

I need to update the docs soon to reflect some of the new workflow.

**Comment by bhundven** [comment]
@Ledest Thanks!

**Pull request merged**
