### PR TITLE
samples: update sparc/leon sample

### PR DESCRIPTION
**Pull request by KirillSmirnov**

### CODE REVIEW

**Comment by stilor** [comment]
Just curious, why you pinned ISL to 0.15 (instead of 0.16.1, default for GCC6)?
Also, why not go to GCC7? You'd need to add `--disable-libcilkrts` though, as the assembly code in libcilkrts is incompatible with `-march=leon` - you might want to submit a bug upstream if you're interested in SPARC LEON.

**Comment by KirillSmirnov** [comment]
ISL 0.15 was generated by 'ct-ng savedefconfig'. I did the following:
1) ct-ng sparc-leon-linux-uclibc
2) ct-ng menuconfig -> changed gcc from 4.9 to 6.3 -> save
3) ct-ng savedefconfig

After your notice I tried another way:
1) edited sample configuration gcc from 4.9 to 6.3
2) ct-ng sparc-leon-linux-uclibc
3) ct-ng savedefconfig

The ISL 0.15 configuration line has gone away.

**Comment by KirillSmirnov** [comment]
I have not tried gcc7 for my leon_nofpu project yet, since I prefer more stable release 6.3.
Indeed, gcc 7 without libcilkrts has been successfully built, toolchain can produce executables, but it may take a couple of days before I can test it on my board.

**Comment by stilor** [comment]
Merged via #733.

**Pull request closed without merging**
