### PR TITLE
gcc: Added 6.1.0 to version list

### PR DESCRIPTION
**Pull request by dajamminyogesh**
added gcc-6.1.0 to version list in kconfig

Signed-off-by: Yogesh Sharma <YogeshASharma@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/crosstool-ng/crosstool-ng/389)

### CODE REVIEW

**Comment by bhundven** [comment]
This still fails to build. Please look at also porting the patches from 5.3.0 forward to 6.1.0.

**Comment by stilor** [comment]
@bhundven Note that one of the commits on multilib PR adds a new patch to GCC (nios2-*-gcc reports a bad multilib default, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70718
Also, I think GCC upgrade should go through build-all test, I can pick up that branch and run it through build-all after multilib integration.

**Comment by dajamminyogesh** [comment]
I migrated all the patches from 5.3.0 to 6.1.0 except for the patches that are OBE or merged into upstream.  Also how do I trigger a build-all test?

**Comment by stilor** [comment]
@dajamminyogesh The patch I am referring to is not yet in the tree, it is pending in another PR awaiting integration. I.e. it is not a flaw in your changes, rather a note that https://github.com/crosstool-ng/crosstool-ng/pull/383 has a soft conflict with your branch.
As to build-all, it is a target in ct-ng: `ct-ng build-all CT_PREFIX=<path where built toolchains are installed>`. It builds all the samples in ct-ng (`ct-ng list-samples`). Note that it takes a very long time - on my machine, it is ~24 hours before PR383 and ~30 hours after.

**Comment by dajamminyogesh** [comment]
do you know how much disk space a build-all takes?I need to make sure my VM is properly sized to handle this.  I want to run the build-all target to make sure I did not break another lib with the c++03 to c++11 default change in gcc 6.1.0.

**Comment by stilor** [comment]
Currently, about 400GB, I think. I didn't measure specifically, so this figure may not be very accurate.
In the multilib PR, one commit reduces that drastically by removing successful build directories:
https://github.com/crosstool-ng/crosstool-ng/pull/383/commits/001a0fe407c4f950114eb29ede9f5ad03ace82b4
In case all samples survive the build, the required space is just what's needed for the largest sample.

**Comment by dajamminyogesh** [comment]
I do not have a machine with enough storage for this operation.  Can we trigger this somehow in travis-ci?

**Comment by stilor** [comment]
@bhundven is understandably reluctant to schedule 24-hour build in Travis :) As I said, there's a patch which reduces the size needed, but it is not picked up yet. You can pick it up locally for testing, or wait until that branch is merged.

**Comment by dajamminyogesh** [comment]
I think the branch was rebased, since the reference to the commit gives me the error:

We went looking everywhere, but couldn’t find those commits.

**Comment by stilor** [comment]
Indeed, there was a rebase due to a review. Now it is commit https://github.com/crosstool-ng/crosstool-ng/pull/383/commits/7c2bdcd6f7bb20817ba12dbdf142a78a1fae1b94

**Comment by dajamminyogesh** [comment]
Awesome.  I cherry-picked the commit and I am building now.  I will post how it goes.

**Comment by dajamminyogesh** [comment]
I am getting a build error with target arm-bare_newlib_cortex_m3_nommu-eabi

It looks like http://cgit.openadk.org/cgi/cgit/elf2flt.git no longer exists.  Do we know where this repo has moved to?

**Comment by bhundven** [comment]
https://github.com/uclinux-dev/elf2flt

**Comment by dajamminyogesh** [comment]
The target references commit 454b6b415a31959661406bdfbd9dad22229367bf which does not exist in that repo.  I am guessing they rebased along with the migration.  Do we know why that revision was selected?

**Comment by bhundven** [comment]
It was a different tree. Please use the latest HEAD. I will add a new PR to update this later.

**Comment by dajamminyogesh** [comment]
A couple of new libs needed for these builds (at least in ubuntu):

python-dev (needed for gdb)
zlib1g-dev (needed for elf2flt)

The python-dev requirement was not obvious from the build error message.

**Comment by bhundven** [comment]
These are both known requirements prior to your change.

**Comment by dajamminyogesh** [comment]
How are we building sample "i586-mingw32msvc,i686-none-linux-gnu" on linux?

I keep getting the error:

[ERROR]  Missing: 'i586-mingw32msvc-ar' or 'i586-mingw32msvc-ar' or 'ar' : either needed!

even though:
$ which ar
/usr/bin/ar
[build.txt](https://github.com/crosstool-ng/crosstool-ng/files/281970/build.txt)

**Comment by stilor** [comment]
Noone knows. This is why it is marked broken :)

**Comment by dajamminyogesh** [comment]
Strange ... it is not marked as broken in ct-ng list-samples:

$ ./install/bin/ct-ng list-samples
Status  Sample name
[G..]   aarch64-rpi3-linux-gnueabi
[G..]   aarch64-unknown-linux-gnueabi
[G..]   alphaev56-unknown-linux-gnu
[G..]   alphaev67-unknown-linux-gnu
[G..]   arm-bare_newlib_cortex_m3_nommu-eabi
[G..]   arm-cortex_a15-linux-gnueabi
[G.X]   arm-cortexa5-linux-uclibcgnueabihf
[G..]   arm-cortex_a8-linux-gnueabi
[G.X]   arm-cortexa9_neon-linux-gnueabihf
[G..]   armeb-unknown-eabi
[G..]   armeb-unknown-linux-gnueabi
[G..]   armeb-unknown-linux-uclibcgnueabi
[G..]   arm-unknown-eabi
[G..]   arm-unknown-linux-gnueabi
[G.X]   arm-unknown-linux-musleabi
[G..]   arm-unknown-linux-uclibcgnueabi
[G.X]   arm-unknown-linux-uclibcgnueabihf
[G..]   armv6-rpi-linux-gnueabi
[G..]   armv7-rpi2-linux-gnueabihf
[G..]   armv8-rpi3-linux-gnueabihf
[G..]   avr
[G..]   i586-geode-linux-uclibc
[G..]   i586-mingw32msvc,i686-none-linux-gnu
[G..]   i686-nptl-linux-gnu
[G.X]   i686-w64-mingw32
[G..]   m68k-unknown-elf
[G..]   m68k-unknown-uclinux-uclibc
[G..]   mips64el-n32-linux-uclibc
[G..]   mips64el-n64-linux-uclibc
[G..]   mips-ar2315-linux-gnu
[G..]   mipsel-sde-elf
[G..]   mipsel-unknown-linux-gnu
[G..]   mips-malta-linux-gnu
[G..]   mips-unknown-elf
[G..]   mips-unknown-linux-uclibc
[G.X]   i686-w64-mingw32,nios2-spico-elf
[G..]   powerpc-405-linux-gnu
[G..]   powerpc64-unknown-linux-gnu
[G..]   powerpc-860-linux-gnu
[G..]   powerpc-e300c3-linux-gnu
[G..]   powerpc-e500v2-linux-gnuspe
[G..]   powerpc-unknown-linux-gnu
[G..]   powerpc-unknown-linux-uclibc
[G..]   powerpc-unknown_nofpu-linux-gnu
[G.X]   s390-ibm-linux-gnu
[G..]   s390x-ibm-linux-gnu
[G..]   sh4-unknown-linux-gnu
[G..]   sparc-unknown-linux-gnu
[G.X]   x86_64-w64-mingw32,x86_64-pc-linux-gnu
[G..]   x86_64-unknown-linux-gnu
[G..]   x86_64-unknown-linux-uclibc
[G.X]   x86_64-w64-mingw32
[G..]   xtensa-unknown-linux-uclibc
 L (Local)       : sample was found in current directory
 G (Global)      : sample was installed with crosstool-NG
 X (EXPERIMENTAL): sample may use EXPERIMENTAL features
 B (BROKEN)      : sample is currently broken

**Comment by stilor** [comment]
It is marked broken if one's using ct-ng locally (i.e. configured with --enable-local). Looks like a bug - 'broken' files are not installed to DESTDIR during 'make install'. @bhundven, is it intentional?

**Comment by dajamminyogesh** [comment]
do we know why s390x-ibm-linux-gnu has CT_PATCH_NONE set?  This causes the build to fail.

**Comment by dajamminyogesh** [comment]
All builds now pass! Is there anything else that I need to do to get this pull request merged?

**Comment by bhundven** [comment]
Currently, everything is blocked by https://github.com/crosstool-ng/crosstool-ng/pull/383 ... so, waiting on that.

**Comment by daniel-thompson** [comment]
Pull #383 was taken a week or two ago so I just wanted to bump this PR...

It doesn't merge cleanly with master: there are conflicts after the upstream version bump of the gcc-5 series to 5.40 and the elf2flt change already landed by a different route. However after solving these trivial issues I was able to build an basic ARM Cortex-M toolchain with the gcc 6.1 .

**Comment by dajamminyogesh** [comment]
Rebased from master.  Can we reopen this.  I am not sure why it closed.

**Comment by dajamminyogesh** [comment]
This build passes (see https://travis-ci.org/dajamminyogesh/crosstool-ng/builds/158189951 ) what is required to get this merged?

**Comment by bhundven** [comment]
Thanks!

**Pull request merged**
