### PR TITLE
fix offsets of gcc 7.2.0 patches

### PR DESCRIPTION
**Pull request by ksergeyv**
Signed-off-by: Sergey Korolev <s.korolev@ndmsystems.com>

### CODE REVIEW

**Comment by stilor** [comment]
I assume you used some kind of a tool (since git commit IDs were also truncated). What is it?

I want to extend test-package.sh to do that for all packages, not just gcc-7.2.0.

**Comment by ksergeyv** [comment]
Unfortunately it is manual work.
Commit IDs probably changed due to `git format-patch` or something I used.
Specifically here https://github.com/crosstool-ng/crosstool-ng/pull/871/commits/fd64d3775c311e44165afc8e0e5d95a3f310f0a5 ID changed due to a context change I suppose.

**Comment by stilor** [comment]
And another question, why did you need this? I thought all these patches still applied, even if at a different offset, so it shouldn't have been a problem for the build.

**Comment by ksergeyv** [comment]
The only nontechnical reason is I do not like warnings (since sometimes these indicate errors) and prefer clean build and compile processes.

**Comment by ksergeyv** [comment]
I suppose `quilt refresh` is an appropriate command to automate such fixes.

**Comment by stilor** [comment]
I figured that much, but I don't want ct-ng to switch to quilt-based patch management completely: unlike debian that needs it only during package build, we'll need it to be available on the end-user's machine. So I guess it would be something like `mkdir tmp-patches; touch tmp-patches/series; quilt setup tmp-patches/series; for p in $CT_LIB_DIR/packages/$pkg/$version/*.patch; do quilt import $p; quilt refresh; done; cp tmp-patches/*.patch $CT_LIB_DIR/packages/$pkg/$version/*.patch`.

I'll merge this for now, but don't waste your time on updating the rest of the patches manually.

**Pull request merged**
