### PR TITLE
Add multiple compiler structure

### PR DESCRIPTION
**Pull request by diorcety**
Prepare ct-ng to support multiple compilers (clang for example)

### CODE REVIEW

**Comment by bhundven** [comment]
@diorcety Can you rebase this? Thanks!

**Comment by diorcety** [comment]
done

**Comment by diorcety** [comment]
Yes sure

**Comment by mingwandroid** [comment]
@bhundven How's 1.20.1 coming along, anything I/we can do to assist with that?

**Comment by bhundven** [comment]
@mingwandroid I'm just slammed with personal life stuff. I need docs updated for 1.20.1, and there are a few bugs that need to be validated/fixed. I'd like to get docs totally rewritten and have been looking at either writing them in markdown or asciidoc, but we can continue that conversation in #44

**Comment by bhundven** [comment]
https://github.com/crosstool-ng/crosstool-ng/milestones/1.20.1

**Comment by bhundven** [comment]
Things with 1.20.1 have taken too long. I wanted to see eglibc gone before I had you rebase yet another time. I'm happy to bypass a 1.20.1 release, and just start on 1.21.0.

The only things left are in my previous comment for the milestones of 1.20.1 and this patch to go with 1.21.0. After that, I plan on reorganizing things a bit to get us to a 2-pass build.

I really could use some more help, if anyone wants to grab one of those bugs and help us move forward to gcc-5.1, latest llvm.

**Comment by bhundven** [comment]
Thanks!

**Pull request merged**
