### PR TITLE
Making libmpx configurable & moving gcc libs: more fixes

### PR DESCRIPTION
**Pull request by stilor**
Recent changes broke x86-*-mingw32, x86-*-musl and m68k-*-uclibc samples.

### CODE REVIEW

**Comment by KirillSmirnov** [comment]
multilib mingw still failing:

libsupc++.a' 
[DEBUG]    ==> Executing: 'mv' '/home/lich/x-tools/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/../lib/libvtv.a' '/home/lich/x-tools/x86_64-w64-mingw32/x86_64-w64-mingw32/sysroot/lib/../lib/libvtv.a' 
[DEBUG]    ==> Executing: 'mv' '/home/lich/x-tools/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/../lib/libvtv_stubs.a' '/home/lich/x-tools/x86_64-w64-mingw32/x86_64-w64-mingw32/sysroot/lib/../lib/libvtv_stubs.a' 
[DEBUG]    Entering 'movelibs_32'
[DEBUG]    ==> Executing: 'mv' '/home/lich/x-tools/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/../lib32/libatomic.a' '/home/lich/x-tools/x86_64-w64-mingw32/x86_64-w64-mingw32/sysroot/lib/../lib32/libatomic.a' 
[ALL  ]    mv: cannot move '/home/lich/x-tools/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/../lib32/libatomic.a' to '/home/lich/x-tools/x86_64-w64-mingw32/x86_64-w64-mingw32/sysroot/lib/../lib32/libatomic.a': No such file or directory

[build.log.zip](https://github.com/crosstool-ng/crosstool-ng/files/516843/build.log.zip)
[config.zip](https://github.com/crosstool-ng/crosstool-ng/files/516845/config.zip)

**Comment by KirillSmirnov** [comment]
False negative, wrong branch again :-(
mingw is OK.

**Comment by stilor** [comment]
@bhundven Ok to merge? Most baremetal & mingw samples currently fail because of these issues.

**Comment by stilor** [comment]
Ping?

**Comment by bhundven** [comment]
The branch is out of date. This seems to happen every time I do a pull request.
There is a button there that You can press to "Update branch". If I had write access to your branch, I could press the "Update branch" button and merge it.

screen shot 2016-10-12 at 11 54 54 am

**Comment by stilor** [comment]
Updated, but now Travis is off building it again.

**Comment by bhundven** [comment]
It's fine. I still need to workout PR workflow issues like this.

**Comment by stilor** [comment]
On an unrelated note (don't know if you're currently on IRC):
<aneyman> I rolled out a mini-travis of my own :) a build script that pulls new commits and rebuild all samples, but limits its runtime to the period when I am not using my workstation
<aneyman> it currently doesn't handle canadian crosses
<aneyman> but I probably can improve it in that aspect
<aneyman> I guess we could have a contrib/ directory in crosstool-ng so that others can start build-testing crosstool-ng in their environments without loading their machine during the times when it is used
<aneyman> also, regarding other things I want in ct-ng: I want to build companion tools for host as well, so that the produced toolchain comes with a defined version of make/m4/whatnot if one wants it
<aneyman> what do you think?

**Comment by stilor** [comment]
Travis failed during download state. Can the builds for failed samples be restarted?

**Comment by bhundven** [comment]
Cleared the caches, restarted the build.

**Comment by stilor** [comment]
Same again on a different set of samples... Travis seems to be unstable.

**Comment by bhundven** [comment]
Come to find out that travis-ci's default build image is ubuntu precise 12.04.
The ssl keys are now out of date enough that kernel.org has already updated their key and now it doesn't match.

Luckily, they have a beta for trusty 14.04. I have #466 open to resolve that issue.

**Pull request merged**
