### PR TITLE
Add powerpc asm fix for glibc 2.19

### PR DESCRIPTION
**Pull request by nikkon-dev**
Integration of the https://patchwork.ozlabs.org/patch/686205/ fix by Joseph Myers

### CODE REVIEW

**Comment by cpackham** [comment]
Build tested `powerpc-unknown-linux-gnu` and `powerpc64-unknown-linux-gnu` both OK.

**Comment by stilor** [comment]
Is it applicable to other glibc versions?

**Comment by spaun2002** [comment]
> Is it applicable to other glibc versions?

Versions that do not have this patch: 2.19, 2.20, 2.21, 2.22, 2.23
The first version with this patch: 2.24 ( https://sourceware.org/git/?p=glibc.git;a=history;f=sysdeps/powerpc/powerpc64/power6/memset.S;h=d445b1e1ef18597635830089d315d9fdeb89bccc;hb=refs/heads/release/2.24/master )

**Comment by nikkon-dev** [comment]
I've added the patch to all GLibc versions that need it. If you can, please double-check that there are no issues with ppc64le target and glibc versions 2.20, 2.21, 2.22, 2.23.
glibc 2.19 was validated before. 
I do not have machines where all affected glibc versions can be validated.

**Pull request merged**
