### PR TITLE
Upgrade uClibc-ng to 1.0.17 (1.0.18 has issues - marked experimental)

### PR DESCRIPTION
**Pull request by stilor**
Tested on top of multilib changes, all uclibc samples build fine.

---
This change is [Reviewable](https://reviewable.io/reviews/crosstool-ng/crosstool-ng/391)

### CODE REVIEW

**Comment by bhundven** [comment]
Do you want to bump this to 1.0.16?

**Comment by bhundven** [comment]
I guess 1.0.17 was just released.

**Comment by stilor** [comment]
I didn't remove 1.0.14 - should I just keep the most recent (1.0.17) or retain 1.0.14 as well?

**Comment by bhundven** [comment]
Just 1.0.17

**Comment by stilor** [comment]
Ping?

**Comment by bhundven** [comment]
Sorry about my delay on some of these PRs. It's hard to find time. If you bump this to 1.0.18, I really will merge this :)

**Comment by stilor** [comment]
So, you're waiting till the next release to point out that the change is outdated. Gotcha! :)

**Comment by bhundven** [comment]
Hah, my bad. I've just been behind. We need to get a ct-ng release out soon.

**Comment by stilor** [comment]
Tested with x86-multilib-linux-uclibc sample, will test the rest overnight.

**Comment by bhundven** [comment]
Thanks!

**Pull request merged**
