### PR TITLE
Add support for Xtensa architecture

### PR DESCRIPTION
**Pull request by jcmvbkbc**
Hi Bryan,

this series adds support for Xtensa architecture to crosstool-NG (issue #243).
There are architecture-specific patches for the latest binutils, gcc and gdb.
Patch for the newlib is not ready for mainline and needs more work.
Please let me know what you think.

### CODE REVIEW

**Comment by bhundven** [comment]
@jcmvbkbc Great! I'm very excited to have this support added!

On question. I just added uClibc-ng 1.0.8, and reworked architecture specific changes in scripts/build/libc/uClibc.sh (manage_uClibc_config()). Is there anything uClibc/uClibc-ng needs for xtensa support?

**Comment by jcmvbkbc** [comment]
> Is there anything uClibc/uClibc-ng needs for xtensa support?

No, currently they don't need anything special.

**Comment by bhundven** [comment]
> No, currently they don't need anything special.

@jcmvbkbc Great!

One last request, two part.

1. Please add a sample, do a build with ct-ng, and when the build completes and works properly, do ```ct-ng saveconfig```, and it should put something like: xtensa-unknown-linux-... in the current directory. Copy that into the samples/ directory and add that to the commit.
    * Bonus points for adding the sample to the .travis.yml file so that we also check this sample when we modify anything in crosstool-ng to make sure we don't break xtensa support! ;)

**Comment by jcmvbkbc** [comment]
Ok, will do both.

**Comment by jcmvbkbc** [comment]
Done.

**Comment by bhundven** [comment]
Thank you!

**Comment by pfalcon** [comment]
@jcmvbkbc : Thanks for handling this! Just to clarify: what about gcc 4.x branch?

**Comment by jcmvbkbc** [comment]
@pfalcon : I see two big options here:
- merge it to the mainline if it's acceptable (a new xtensa-specific feature addition to gcc-4.8)
- merge mainline back to my branches to fix issues of the old baseline.

Even if merging it to mainline is possible it still wouldn't be complete until newlib is done.

**Comment by pfalcon** [comment]
@jcmvbkbc : I'd consider both options good, but if it can be merged into mainline, and that's easy enough (as this PR shows) - why not? As @bhundven told, he's going to keep maintaining only the last micro version of each 4.7.x, 4.8.x, 4.9.x, but I'm sure there's no talk about dropping those gcc branches any time soon (and I assume any patches would be easily portable across micro versions (though may be worth asking @bhundven what maintenance involvement he expects from contributors)).

And choosing gcc 4.8 for xtensa support is good too - indeed, aggressive undefined behavior optimizations started in 4.9.

P.S. Sorry I can't directly test your patches now, as going from sickness into travel. I'll do that as soon as I can. I also pinged folks like @projectgus and @foogod to have a look too.

**Comment by bhundven** [comment]
@pfalcon I'll maintain any branch as long as someone is willing to do the work.
I'm focused on the master branch and moving ct-ng forward.
I'd prefer that patches to make architectures work properly to be pushed upstream (gcc, glibc, binutils, newlib, etc...), as my job is not to maintain patches, but ct-ng itself.

**Comment by jcmvbkbc** [comment]
@pfalcon : ok, second option for now: 1.22.0-based branch with support for esp8266 and esp32 (configurations called xtensa-lx106-elf and xtensa-esp108-elf with binutils-2.25.1, gcc-4.8.5, gdb-7.10) is here: https://github.com/jcmvbkbc/crosstool-NG/tree/xtensa-1.22.x

**Comment by bhundven** [comment]
4.8.5 will still be available after #222 is complete. The supported versions will be: 4.8.5, 4.9.3 (I see work happening for 4.9.4 in https://gcc.gnu.org/bugzilla/), and 5.x.

https://github.com/crosstool-ng/crosstool-ng/tree/master/patches/gcc/4.8.5  << there are xtensa patches from buildroot in the 4.8.5 patch tree, so it is possible to support 4.8.x in crosstool-ng mainline.

**Comment by jcmvbkbc** [comment]
@bhundven unfortunately there were no support for call0 Xtensa ABI in gcc prior to 5.x, and its support is crucial for esp8266.
With gcc-5.x the only issue is the newlib. The newlib port is rather dirty: e.g. it breaks build for other architectures. I hope to clean it up in late December and try to upstream it.

**Comment by bhundven** [comment]
Is it too difficult to backport call0 support from 5.x to 4.9.x/4.8.x?

**Comment by jcmvbkbc** [comment]
It's not. In fact it was initially developed for 4.8.2.

**Comment by bhundven** [comment]
As you can see in #282, 4.8.5 will be around for a while if you want to backport this support.

**Pull request merged**
